package config

// roomLevelNameMap mirrors the roomName values from wgServer/src/qp/games/*/config.ts.
// Keyed by game symbol then room level — same level can have different names across games.
// Some games expose multiple room configs for the same level; we keep the first entry.
var roomLevelNameMap = map[string]map[uint32]string{
	"adbh": {
		1:  "Andar Bahar Bronze",
		2:  "Andar Bahar Silver",
		3:  "Andar Bahar Gold",
		4:  "Andar Bahar Platinum",
		5:  "Andar Bahar Diamond",
		99: "Andar Bahar Trial",
	},
	"bcbm": {
		1: "BCBM Bronze",
		2: "BCBM Silver",
		3: "BCBM Gold",
		4: "BCBM Platinum",
		5: "BCBM Diamond",
	},
	"bjl": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"br_nn": {
		1: "BRNN x3 Bronze",
		2: "BRNN x3 Silver",
		3: "BRNN x3 Gold",
	},
	"chjk2": {
		1: "CHJK2 Room 1",
		2: "CHJK2 Room 2",
		3: "CHJK2 Room 3",
		4: "CHJK2 Room 4",
		5: "CHJK2 Room 5",
	},
	"ddx": {
		1: "DDX Bronze",
		2: "DDX Silver",
		3: "DDX Gold",
		4: "DDX Platinum",
		5: "DDX Diamond",
		6: "DDX Trial",
	},
	"dzpk": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"ebg": {
		1: "体验场",
		2: "初级场",
		3: "中级场",
		4: "高级场",
		5: "大师场",
	},
	"ermj": {
		1: "体验场",
		2: "娱乐场",
		3: "旗舰场",
		4: "富豪场",
		5: "至尊场",
	},
	"fqzs": {
		1: "FQZS Bronze",
		2: "FQZS Silver",
		3: "FQZS Gold",
		4: "FQZS Platinum",
		5: "FQZS Diamond",
	},
	"hhdz": {
		1: "HHDZ Bronze",
		2: "HHDZ Silver",
		3: "HHDZ Gold",
		4: "HHDZ Platinum",
		5: "HHDZ Diamond",
	},
	"jd_ddz": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"kp_nn": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"ksznn": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"lhd": {
		1: "体验房",
		2: "娱乐房",
		3: "高级房",
		4: "豪华房",
		5: "尊享房",
	},
	"qz_nn": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"qzsg": {
		1: "体验场",
		2: "初级场",
		3: "中级场",
		4: "高级场",
		5: "大师场",
	},
	"roulette": {
		1: "Roulette Bronze",
		2: "Roulette Silver",
		3: "Roulette Gold",
		4: "Roulette Platinum",
		5: "Roulette Diamond",
		6: "Roulette Trial",
	},
	"rummy": {
		1: "Rummy Room 1",
		2: "Rummy Room 2",
		3: "Rummy Room 3",
		4: "Rummy Room 4",
		5: "Rummy Room 5",
	},
	"slhb": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"slhb2": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"slwh": {
		1: "SLWH Bronze",
		2: "SLWH Silver",
		3: "SLWH Gold",
		4: "SLWH Platinum",
		5: "SLWH Diamond",
		6: "SLWH Trial",
	},
	"sss": {
		1: "Experience Room",
		2: "Fun Room",
		3: "Pro Room",
		4: "VIP Room",
		5: "Master Room",
	},
	"sud": {
		1: "SUD Bronze",
		2: "SUD Silver",
		3: "SUD Gold",
		4: "SUD Platinum",
		5: "SUD Diamond",
		6: "SUD Trial",
	},
	"tb2": {
		1: "TB2 Bronze",
		2: "TB2 Silver",
		3: "TB2 Gold",
		4: "TB2 Platinum",
		5: "TB2 Diamond",
		6: "TB2 Trial",
	},
	"tb_nn": {
		1: "体验厅",
		2: "娱乐厅",
		3: "旗舰厅",
		4: "富豪厅",
		5: "至尊厅",
	},
	"teenpatti": {
		1: "Teen Patti Room 1",
		2: "Teen Patti Room 2",
		3: "Teen Patti Room 3",
		4: "Teen Patti Room 4",
		5: "Teen Patti Room 5",
	},
	"ysdx": {
		1:  "YSDX Bronze",
		2:  "YSDX Silver",
		3:  "YSDX Gold",
		4:  "YSDX Platinum",
		5:  "YSDX Diamond",
		99: "YSDX Trial",
	},
	"yxx": {
		1: "Fish Prawn Crab Bronze",
		2: "Fish Prawn Crab Silver",
		3: "Fish Prawn Crab Gold",
		4: "Fish Prawn Crab Platinum",
		5: "Fish Prawn Crab Diamond",
		6: "Fish Prawn Crab Trial",
	},
	"zjh": {
		1: "体验场",
		2: "娱乐场",
		3: "豪华场",
		4: "富豪场",
		5: "至尊场",
	},
}
