syntax = "proto3";

option go_package = "./services;services";

package datacenter;

import "player.proto";
import "base.proto";

service DataCenterService {
    //获取玩家信息
    rpc GetPlayer (GetPlayerReq) returns (GetPlayerResp);
    //获取指定键值
    rpc GetValue (GetValueReq) returns (GetValueResp);
    //缓存
    rpc SetValue (SetValueReq) returns (SetValueResp);
    //修改玩家信息
    rpc UpdatePlayerAvatarAndGender (UpdatePlayerAvatarAndGenderReq) returns (UpdatePlayerAvatarAndGenderResp);
    //获取注单信息
    rpc GetRecords(GetRecordsReq) returns (GetRecordsResp);
    //获取游戏列表
    rpc GetGameList(GetGameListReq) returns (GetGameListResp);
    //加锁
    rpc UserLock(UserLockReq) returns (UserLockResp);
    //解锁
    rpc UserUnLock(UserUnLockReq) returns (UserUnLockResp);
    //获取session
    rpc GetSesson(GetSessionReq) returns (GetSessionResp);
    //保存哈希开奖结果
    rpc SaveHashLotteryResult(SaveHashLotteryResultReq) returns (SaveHashLotteryResultResp);
    //获取哈希开奖结果
    rpc GetHashLotteryResult(GetHashLotteryResultReq) returns (GetHashLotteryResultResp);
    //获取游戏开奖记录列表
    rpc GetGameRecordsList(GetGameRecordsListReq) returns (GetGameRecordsListResp);
}

message GetSessionReq {
    string key = 1;
    int64 timeOut = 2;
}

message GetSessionResp {
    base.error_code code = 1;
    string value = 2;
}

message SaveHashLotteryResultReq {
    int32 gameId = 1;
    string seed = 2;
    string value = 3;
}

message SaveHashLotteryResultResp {
    base.error_code code = 1;
}

message GetHashLotteryResultReq {
    int32 gameId = 1;
    string seed = 2;
}

message GetHashLotteryResultResp {
    base.error_code code = 1;
    string str = 2;
}

message GetGameRecordsListReq {
    int32 gameId = 1;
    int32 userId = 2;
    bool isWinGold = 3;
}

message GetGameRecordsListResp {
    base.error_code code = 1;
    repeated string records = 2;
}

message GetGameListReq {

}

message GetGameListResp {
    base.error_code code = 1;
    //热门游戏的symbol
    repeated string hot = 2;
    //新游戏
    repeated string new = 3;
    //推荐游戏
    repeated string recommend = 4;
    //所有游戏及状态
    repeated GameInfoItem all = 5;

    message GameInfoItem {
        //游戏标志
        string symbol = 1;
        //游戏状态 1 正常 2 维护
        int32 state = 2;
    }
}

message UserLockReq {
    uint32 userId = 1;
}

message UserLockResp {
    string result = 1;
}

message UserUnLockReq {
    uint32 userId = 1;
    string token = 2;
}

message UserUnLockResp {
    bool result = 1;
}

message GetRecordsReq {
    int64 UserId = 1;
    string Symbol = 2;
    string Hash = 3; //hash不为空，则以hash为准忽略其他参数
}

message RecordItem {
    uint32 agentId = 1; //代理id
    uint32 userId = 2; //玩家id
    double bet = 3; //有效下注
    string currency = 4;
    string currencySymbol = 5;
    double base_bet = 6;
    double win = 7;
    double rtp = 8;
    int64 playedDate = 9;
    string roundID = 10;
    string init = 11;
    repeated RecordLog log = 12; //详细
    string symbol = 13; //游戏id
    double balance = 14;
    double balance_cash = 15;
    double balance_bonus = 16;
    string hash = 17;
}

message GetRecordsResp {
    base.error_code code = 1;
    repeated RecordItem data = 2;
}

message RecordLog {
    string cr = 1;
    string sr = 2;
    string roundId = 3;
}

message GetPlayerReq {
    uint32 PlayerId = 1;
    uint32 Factory = 2;
}

message GetPlayerResp {
    player.HumanPlayer HumanPlayer = 1;
}

message GetValueReq {
    string key = 1;
    int64 timeOut = 2;
}

message GetValueResp {
    base.error_code code = 1;
    string value = 2;
}

message SetValueReq {
    string key = 1;
    string value = 2;
    int32 time_out = 3;
}

message SetValueResp {
    base.error_code code = 1;
}

message UpdatePlayerAvatarAndGenderReq {
    uint32 PlayerId = 1;
    string Avatar = 2;
    uint32 Gender = 3;
    uint32 Factory = 4;
    string head_frame = 5;
    string name = 6; //昵称
}

message UpdatePlayerAvatarAndGenderResp {

}
