// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: base.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                   ErrorCode = 0
	ErrorCode_GAME_FROZEN          ErrorCode = 1 //游戏暂停服务
	ErrorCode_AGENT_FROZEN         ErrorCode = 2 //代理被冻结
	ErrorCode_SYSTEM_ERROR         ErrorCode = 3 //系统错误
	ErrorCode_PARAMS_INVALID       ErrorCode = 4
	ErrorCode_USER_LOGIN_ERROR     ErrorCode = 5
	ErrorCode_AUTH_PARSING_FAILED  ErrorCode = 6
	ErrorCode_AUTH_TOKEN_INVALID   ErrorCode = 7
	ErrorCode_NO_ENOUGH_POOL_MONEY ErrorCode = 8 //没有足够水池值
	ErrorCode_NO_ENOUGH_MONEY      ErrorCode = 9 //金币不足
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "GAME_FROZEN",
		2: "AGENT_FROZEN",
		3: "SYSTEM_ERROR",
		4: "PARAMS_INVALID",
		5: "USER_LOGIN_ERROR",
		6: "AUTH_PARSING_FAILED",
		7: "AUTH_TOKEN_INVALID",
		8: "NO_ENOUGH_POOL_MONEY",
		9: "NO_ENOUGH_MONEY",
	}
	ErrorCode_value = map[string]int32{
		"OK":                   0,
		"GAME_FROZEN":          1,
		"AGENT_FROZEN":         2,
		"SYSTEM_ERROR":         3,
		"PARAMS_INVALID":       4,
		"USER_LOGIN_ERROR":     5,
		"AUTH_PARSING_FAILED":  6,
		"AUTH_TOKEN_INVALID":   7,
		"NO_ENOUGH_POOL_MONEY": 8,
		"NO_ENOUGH_MONEY":      9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_base_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_base_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

var File_base_proto protoreflect.FileDescriptor

const file_base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"base.proto\x12\x04base*\xd3\x01\n" +
	"\n" +
	"error_code\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0f\n" +
	"\vGAME_FROZEN\x10\x01\x12\x10\n" +
	"\fAGENT_FROZEN\x10\x02\x12\x10\n" +
	"\fSYSTEM_ERROR\x10\x03\x12\x12\n" +
	"\x0ePARAMS_INVALID\x10\x04\x12\x14\n" +
	"\x10USER_LOGIN_ERROR\x10\x05\x12\x17\n" +
	"\x13AUTH_PARSING_FAILED\x10\x06\x12\x16\n" +
	"\x12AUTH_TOKEN_INVALID\x10\a\x12\x18\n" +
	"\x14NO_ENOUGH_POOL_MONEY\x10\b\x12\x13\n" +
	"\x0fNO_ENOUGH_MONEY\x10\tB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_base_proto_rawDescOnce sync.Once
	file_base_proto_rawDescData []byte
)

func file_base_proto_rawDescGZIP() []byte {
	file_base_proto_rawDescOnce.Do(func() {
		file_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)))
	})
	return file_base_proto_rawDescData
}

var file_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_base_proto_goTypes = []any{
	(ErrorCode)(0), // 0: base.error_code
}
var file_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		EnumInfos:         file_base_proto_enumTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
