// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: datacenter.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataCenterService_GetPlayer_FullMethodName                   = "/datacenter.DataCenterService/GetPlayer"
	DataCenterService_GetValue_FullMethodName                    = "/datacenter.DataCenterService/GetValue"
	DataCenterService_SetValue_FullMethodName                    = "/datacenter.DataCenterService/SetValue"
	DataCenterService_UpdatePlayerAvatarAndGender_FullMethodName = "/datacenter.DataCenterService/UpdatePlayerAvatarAndGender"
	DataCenterService_GetRecords_FullMethodName                  = "/datacenter.DataCenterService/GetRecords"
	DataCenterService_GetGameList_FullMethodName                 = "/datacenter.DataCenterService/GetGameList"
	DataCenterService_UserLock_FullMethodName                    = "/datacenter.DataCenterService/UserLock"
	DataCenterService_UserUnLock_FullMethodName                  = "/datacenter.DataCenterService/UserUnLock"
	DataCenterService_GetSesson_FullMethodName                   = "/datacenter.DataCenterService/GetSesson"
	DataCenterService_SaveHashLotteryResult_FullMethodName       = "/datacenter.DataCenterService/SaveHashLotteryResult"
	DataCenterService_GetHashLotteryResult_FullMethodName        = "/datacenter.DataCenterService/GetHashLotteryResult"
	DataCenterService_GetGameRecordsList_FullMethodName          = "/datacenter.DataCenterService/GetGameRecordsList"
)

// DataCenterServiceClient is the client API for DataCenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataCenterServiceClient interface {
	// 获取玩家信息
	GetPlayer(ctx context.Context, in *GetPlayerReq, opts ...grpc.CallOption) (*GetPlayerResp, error)
	// 获取指定键值
	GetValue(ctx context.Context, in *GetValueReq, opts ...grpc.CallOption) (*GetValueResp, error)
	// 缓存
	SetValue(ctx context.Context, in *SetValueReq, opts ...grpc.CallOption) (*SetValueResp, error)
	// 修改玩家信息
	UpdatePlayerAvatarAndGender(ctx context.Context, in *UpdatePlayerAvatarAndGenderReq, opts ...grpc.CallOption) (*UpdatePlayerAvatarAndGenderResp, error)
	// 获取注单信息
	GetRecords(ctx context.Context, in *GetRecordsReq, opts ...grpc.CallOption) (*GetRecordsResp, error)
	// 获取游戏列表
	GetGameList(ctx context.Context, in *GetGameListReq, opts ...grpc.CallOption) (*GetGameListResp, error)
	// 加锁
	UserLock(ctx context.Context, in *UserLockReq, opts ...grpc.CallOption) (*UserLockResp, error)
	// 解锁
	UserUnLock(ctx context.Context, in *UserUnLockReq, opts ...grpc.CallOption) (*UserUnLockResp, error)
	// 获取session
	GetSesson(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionResp, error)
	// 保存哈希开奖结果
	SaveHashLotteryResult(ctx context.Context, in *SaveHashLotteryResultReq, opts ...grpc.CallOption) (*SaveHashLotteryResultResp, error)
	// 获取哈希开奖结果
	GetHashLotteryResult(ctx context.Context, in *GetHashLotteryResultReq, opts ...grpc.CallOption) (*GetHashLotteryResultResp, error)
	// 获取游戏开奖记录列表
	GetGameRecordsList(ctx context.Context, in *GetGameRecordsListReq, opts ...grpc.CallOption) (*GetGameRecordsListResp, error)
}

type dataCenterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataCenterServiceClient(cc grpc.ClientConnInterface) DataCenterServiceClient {
	return &dataCenterServiceClient{cc}
}

func (c *dataCenterServiceClient) GetPlayer(ctx context.Context, in *GetPlayerReq, opts ...grpc.CallOption) (*GetPlayerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerResp)
	err := c.cc.Invoke(ctx, DataCenterService_GetPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetValue(ctx context.Context, in *GetValueReq, opts ...grpc.CallOption) (*GetValueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResp)
	err := c.cc.Invoke(ctx, DataCenterService_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) SetValue(ctx context.Context, in *SetValueReq, opts ...grpc.CallOption) (*SetValueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetValueResp)
	err := c.cc.Invoke(ctx, DataCenterService_SetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) UpdatePlayerAvatarAndGender(ctx context.Context, in *UpdatePlayerAvatarAndGenderReq, opts ...grpc.CallOption) (*UpdatePlayerAvatarAndGenderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlayerAvatarAndGenderResp)
	err := c.cc.Invoke(ctx, DataCenterService_UpdatePlayerAvatarAndGender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetRecords(ctx context.Context, in *GetRecordsReq, opts ...grpc.CallOption) (*GetRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecordsResp)
	err := c.cc.Invoke(ctx, DataCenterService_GetRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetGameList(ctx context.Context, in *GetGameListReq, opts ...grpc.CallOption) (*GetGameListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameListResp)
	err := c.cc.Invoke(ctx, DataCenterService_GetGameList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) UserLock(ctx context.Context, in *UserLockReq, opts ...grpc.CallOption) (*UserLockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLockResp)
	err := c.cc.Invoke(ctx, DataCenterService_UserLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) UserUnLock(ctx context.Context, in *UserUnLockReq, opts ...grpc.CallOption) (*UserUnLockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUnLockResp)
	err := c.cc.Invoke(ctx, DataCenterService_UserUnLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetSesson(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResp)
	err := c.cc.Invoke(ctx, DataCenterService_GetSesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) SaveHashLotteryResult(ctx context.Context, in *SaveHashLotteryResultReq, opts ...grpc.CallOption) (*SaveHashLotteryResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveHashLotteryResultResp)
	err := c.cc.Invoke(ctx, DataCenterService_SaveHashLotteryResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetHashLotteryResult(ctx context.Context, in *GetHashLotteryResultReq, opts ...grpc.CallOption) (*GetHashLotteryResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHashLotteryResultResp)
	err := c.cc.Invoke(ctx, DataCenterService_GetHashLotteryResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetGameRecordsList(ctx context.Context, in *GetGameRecordsListReq, opts ...grpc.CallOption) (*GetGameRecordsListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameRecordsListResp)
	err := c.cc.Invoke(ctx, DataCenterService_GetGameRecordsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataCenterServiceServer is the server API for DataCenterService service.
// All implementations must embed UnimplementedDataCenterServiceServer
// for forward compatibility.
type DataCenterServiceServer interface {
	// 获取玩家信息
	GetPlayer(context.Context, *GetPlayerReq) (*GetPlayerResp, error)
	// 获取指定键值
	GetValue(context.Context, *GetValueReq) (*GetValueResp, error)
	// 缓存
	SetValue(context.Context, *SetValueReq) (*SetValueResp, error)
	// 修改玩家信息
	UpdatePlayerAvatarAndGender(context.Context, *UpdatePlayerAvatarAndGenderReq) (*UpdatePlayerAvatarAndGenderResp, error)
	// 获取注单信息
	GetRecords(context.Context, *GetRecordsReq) (*GetRecordsResp, error)
	// 获取游戏列表
	GetGameList(context.Context, *GetGameListReq) (*GetGameListResp, error)
	// 加锁
	UserLock(context.Context, *UserLockReq) (*UserLockResp, error)
	// 解锁
	UserUnLock(context.Context, *UserUnLockReq) (*UserUnLockResp, error)
	// 获取session
	GetSesson(context.Context, *GetSessionReq) (*GetSessionResp, error)
	// 保存哈希开奖结果
	SaveHashLotteryResult(context.Context, *SaveHashLotteryResultReq) (*SaveHashLotteryResultResp, error)
	// 获取哈希开奖结果
	GetHashLotteryResult(context.Context, *GetHashLotteryResultReq) (*GetHashLotteryResultResp, error)
	// 获取游戏开奖记录列表
	GetGameRecordsList(context.Context, *GetGameRecordsListReq) (*GetGameRecordsListResp, error)
	mustEmbedUnimplementedDataCenterServiceServer()
}

// UnimplementedDataCenterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataCenterServiceServer struct{}

func (UnimplementedDataCenterServiceServer) GetPlayer(context.Context, *GetPlayerReq) (*GetPlayerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayer not implemented")
}
func (UnimplementedDataCenterServiceServer) GetValue(context.Context, *GetValueReq) (*GetValueResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedDataCenterServiceServer) SetValue(context.Context, *SetValueReq) (*SetValueResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedDataCenterServiceServer) UpdatePlayerAvatarAndGender(context.Context, *UpdatePlayerAvatarAndGenderReq) (*UpdatePlayerAvatarAndGenderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlayerAvatarAndGender not implemented")
}
func (UnimplementedDataCenterServiceServer) GetRecords(context.Context, *GetRecordsReq) (*GetRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecords not implemented")
}
func (UnimplementedDataCenterServiceServer) GetGameList(context.Context, *GetGameListReq) (*GetGameListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameList not implemented")
}
func (UnimplementedDataCenterServiceServer) UserLock(context.Context, *UserLockReq) (*UserLockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserLock not implemented")
}
func (UnimplementedDataCenterServiceServer) UserUnLock(context.Context, *UserUnLockReq) (*UserUnLockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserUnLock not implemented")
}
func (UnimplementedDataCenterServiceServer) GetSesson(context.Context, *GetSessionReq) (*GetSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSesson not implemented")
}
func (UnimplementedDataCenterServiceServer) SaveHashLotteryResult(context.Context, *SaveHashLotteryResultReq) (*SaveHashLotteryResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveHashLotteryResult not implemented")
}
func (UnimplementedDataCenterServiceServer) GetHashLotteryResult(context.Context, *GetHashLotteryResultReq) (*GetHashLotteryResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHashLotteryResult not implemented")
}
func (UnimplementedDataCenterServiceServer) GetGameRecordsList(context.Context, *GetGameRecordsListReq) (*GetGameRecordsListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameRecordsList not implemented")
}
func (UnimplementedDataCenterServiceServer) mustEmbedUnimplementedDataCenterServiceServer() {}
func (UnimplementedDataCenterServiceServer) testEmbeddedByValue()                           {}

// UnsafeDataCenterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataCenterServiceServer will
// result in compilation errors.
type UnsafeDataCenterServiceServer interface {
	mustEmbedUnimplementedDataCenterServiceServer()
}

func RegisterDataCenterServiceServer(s grpc.ServiceRegistrar, srv DataCenterServiceServer) {
	// If the following call panics, it indicates UnimplementedDataCenterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataCenterService_ServiceDesc, srv)
}

func _DataCenterService_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_GetPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetPlayer(ctx, req.(*GetPlayerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetValue(ctx, req.(*GetValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).SetValue(ctx, req.(*SetValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_UpdatePlayerAvatarAndGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerAvatarAndGenderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).UpdatePlayerAvatarAndGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_UpdatePlayerAvatarAndGender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).UpdatePlayerAvatarAndGender(ctx, req.(*UpdatePlayerAvatarAndGenderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_GetRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetRecords(ctx, req.(*GetRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetGameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetGameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_GetGameList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetGameList(ctx, req.(*GetGameListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_UserLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).UserLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_UserLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).UserLock(ctx, req.(*UserLockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_UserUnLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUnLockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).UserUnLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_UserUnLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).UserUnLock(ctx, req.(*UserUnLockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetSesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetSesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_GetSesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetSesson(ctx, req.(*GetSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_SaveHashLotteryResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveHashLotteryResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).SaveHashLotteryResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_SaveHashLotteryResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).SaveHashLotteryResult(ctx, req.(*SaveHashLotteryResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetHashLotteryResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHashLotteryResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetHashLotteryResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_GetHashLotteryResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetHashLotteryResult(ctx, req.(*GetHashLotteryResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetGameRecordsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRecordsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetGameRecordsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCenterService_GetGameRecordsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetGameRecordsList(ctx, req.(*GetGameRecordsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DataCenterService_ServiceDesc is the grpc.ServiceDesc for DataCenterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataCenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datacenter.DataCenterService",
	HandlerType: (*DataCenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayer",
			Handler:    _DataCenterService_GetPlayer_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _DataCenterService_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _DataCenterService_SetValue_Handler,
		},
		{
			MethodName: "UpdatePlayerAvatarAndGender",
			Handler:    _DataCenterService_UpdatePlayerAvatarAndGender_Handler,
		},
		{
			MethodName: "GetRecords",
			Handler:    _DataCenterService_GetRecords_Handler,
		},
		{
			MethodName: "GetGameList",
			Handler:    _DataCenterService_GetGameList_Handler,
		},
		{
			MethodName: "UserLock",
			Handler:    _DataCenterService_UserLock_Handler,
		},
		{
			MethodName: "UserUnLock",
			Handler:    _DataCenterService_UserUnLock_Handler,
		},
		{
			MethodName: "GetSesson",
			Handler:    _DataCenterService_GetSesson_Handler,
		},
		{
			MethodName: "SaveHashLotteryResult",
			Handler:    _DataCenterService_SaveHashLotteryResult_Handler,
		},
		{
			MethodName: "GetHashLotteryResult",
			Handler:    _DataCenterService_GetHashLotteryResult_Handler,
		},
		{
			MethodName: "GetGameRecordsList",
			Handler:    _DataCenterService_GetGameRecordsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datacenter.proto",
}
