// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: datacenter.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TimeOut       int64                  `protobuf:"varint,2,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionReq) Reset() {
	*x = GetSessionReq{}
	mi := &file_datacenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionReq) ProtoMessage() {}

func (x *GetSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionReq.ProtoReflect.Descriptor instead.
func (*GetSessionReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetSessionReq) GetTimeOut() int64 {
	if x != nil {
		return x.TimeOut
	}
	return 0
}

type GetSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResp) Reset() {
	*x = GetSessionResp{}
	mi := &file_datacenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResp) ProtoMessage() {}

func (x *GetSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResp.ProtoReflect.Descriptor instead.
func (*GetSessionResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetSessionResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SaveHashLotteryResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Seed          string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHashLotteryResultReq) Reset() {
	*x = SaveHashLotteryResultReq{}
	mi := &file_datacenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHashLotteryResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHashLotteryResultReq) ProtoMessage() {}

func (x *SaveHashLotteryResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHashLotteryResultReq.ProtoReflect.Descriptor instead.
func (*SaveHashLotteryResultReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{2}
}

func (x *SaveHashLotteryResultReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SaveHashLotteryResultReq) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *SaveHashLotteryResultReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SaveHashLotteryResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHashLotteryResultResp) Reset() {
	*x = SaveHashLotteryResultResp{}
	mi := &file_datacenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHashLotteryResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHashLotteryResultResp) ProtoMessage() {}

func (x *SaveHashLotteryResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHashLotteryResultResp.ProtoReflect.Descriptor instead.
func (*SaveHashLotteryResultResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{3}
}

func (x *SaveHashLotteryResultResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type GetHashLotteryResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Seed          string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHashLotteryResultReq) Reset() {
	*x = GetHashLotteryResultReq{}
	mi := &file_datacenter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHashLotteryResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashLotteryResultReq) ProtoMessage() {}

func (x *GetHashLotteryResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashLotteryResultReq.ProtoReflect.Descriptor instead.
func (*GetHashLotteryResultReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{4}
}

func (x *GetHashLotteryResultReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetHashLotteryResultReq) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

type GetHashLotteryResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Str           string                 `protobuf:"bytes,2,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHashLotteryResultResp) Reset() {
	*x = GetHashLotteryResultResp{}
	mi := &file_datacenter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHashLotteryResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashLotteryResultResp) ProtoMessage() {}

func (x *GetHashLotteryResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashLotteryResultResp.ProtoReflect.Descriptor instead.
func (*GetHashLotteryResultResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{5}
}

func (x *GetHashLotteryResultResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetHashLotteryResultResp) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type GetGameRecordsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	IsWinGold     bool                   `protobuf:"varint,3,opt,name=isWinGold,proto3" json:"isWinGold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRecordsListReq) Reset() {
	*x = GetGameRecordsListReq{}
	mi := &file_datacenter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRecordsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRecordsListReq) ProtoMessage() {}

func (x *GetGameRecordsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRecordsListReq.ProtoReflect.Descriptor instead.
func (*GetGameRecordsListReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{6}
}

func (x *GetGameRecordsListReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetGameRecordsListReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGameRecordsListReq) GetIsWinGold() bool {
	if x != nil {
		return x.IsWinGold
	}
	return false
}

type GetGameRecordsListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Records       []string               `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRecordsListResp) Reset() {
	*x = GetGameRecordsListResp{}
	mi := &file_datacenter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRecordsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRecordsListResp) ProtoMessage() {}

func (x *GetGameRecordsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRecordsListResp.ProtoReflect.Descriptor instead.
func (*GetGameRecordsListResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameRecordsListResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetGameRecordsListResp) GetRecords() []string {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetGameListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListReq) Reset() {
	*x = GetGameListReq{}
	mi := &file_datacenter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListReq) ProtoMessage() {}

func (x *GetGameListReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListReq.ProtoReflect.Descriptor instead.
func (*GetGameListReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{8}
}

type GetGameListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	// 热门游戏的symbol
	Hot []string `protobuf:"bytes,2,rep,name=hot,proto3" json:"hot,omitempty"`
	// 新游戏
	New []string `protobuf:"bytes,3,rep,name=new,proto3" json:"new,omitempty"`
	// 推荐游戏
	Recommend []string `protobuf:"bytes,4,rep,name=recommend,proto3" json:"recommend,omitempty"`
	// 所有游戏及状态
	All           []*GetGameListResp_GameInfoItem `protobuf:"bytes,5,rep,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListResp) Reset() {
	*x = GetGameListResp{}
	mi := &file_datacenter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResp) ProtoMessage() {}

func (x *GetGameListResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResp.ProtoReflect.Descriptor instead.
func (*GetGameListResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameListResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetGameListResp) GetHot() []string {
	if x != nil {
		return x.Hot
	}
	return nil
}

func (x *GetGameListResp) GetNew() []string {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *GetGameListResp) GetRecommend() []string {
	if x != nil {
		return x.Recommend
	}
	return nil
}

func (x *GetGameListResp) GetAll() []*GetGameListResp_GameInfoItem {
	if x != nil {
		return x.All
	}
	return nil
}

type UserLockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLockReq) Reset() {
	*x = UserLockReq{}
	mi := &file_datacenter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLockReq) ProtoMessage() {}

func (x *UserLockReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLockReq.ProtoReflect.Descriptor instead.
func (*UserLockReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{10}
}

func (x *UserLockReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserLockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLockResp) Reset() {
	*x = UserLockResp{}
	mi := &file_datacenter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLockResp) ProtoMessage() {}

func (x *UserLockResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLockResp.ProtoReflect.Descriptor instead.
func (*UserLockResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{11}
}

func (x *UserLockResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UserUnLockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnLockReq) Reset() {
	*x = UserUnLockReq{}
	mi := &file_datacenter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnLockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnLockReq) ProtoMessage() {}

func (x *UserUnLockReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnLockReq.ProtoReflect.Descriptor instead.
func (*UserUnLockReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{12}
}

func (x *UserUnLockReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUnLockReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserUnLockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnLockResp) Reset() {
	*x = UserUnLockResp{}
	mi := &file_datacenter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnLockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnLockResp) ProtoMessage() {}

func (x *UserUnLockResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnLockResp.ProtoReflect.Descriptor instead.
func (*UserUnLockResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{13}
}

func (x *UserUnLockResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetRecordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"` //hash不为空，则以hash为准忽略其他参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsReq) Reset() {
	*x = GetRecordsReq{}
	mi := &file_datacenter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsReq) ProtoMessage() {}

func (x *GetRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsReq.ProtoReflect.Descriptor instead.
func (*GetRecordsReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{14}
}

func (x *GetRecordsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecordsReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetRecordsReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type RecordItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        uint32                 `protobuf:"varint,1,opt,name=agentId,proto3" json:"agentId,omitempty"` //代理id
	UserId         uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`   //玩家id
	Bet            float64                `protobuf:"fixed64,3,opt,name=bet,proto3" json:"bet,omitempty"`        //有效下注
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,5,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	BaseBet        float64                `protobuf:"fixed64,6,opt,name=base_bet,json=baseBet,proto3" json:"base_bet,omitempty"`
	Win            float64                `protobuf:"fixed64,7,opt,name=win,proto3" json:"win,omitempty"`
	Rtp            float64                `protobuf:"fixed64,8,opt,name=rtp,proto3" json:"rtp,omitempty"`
	PlayedDate     int64                  `protobuf:"varint,9,opt,name=playedDate,proto3" json:"playedDate,omitempty"`
	RoundID        string                 `protobuf:"bytes,10,opt,name=roundID,proto3" json:"roundID,omitempty"`
	Init           string                 `protobuf:"bytes,11,opt,name=init,proto3" json:"init,omitempty"`
	Log            []*RecordLog           `protobuf:"bytes,12,rep,name=log,proto3" json:"log,omitempty"`       //详细
	Symbol         string                 `protobuf:"bytes,13,opt,name=symbol,proto3" json:"symbol,omitempty"` //游戏id
	Balance        float64                `protobuf:"fixed64,14,opt,name=balance,proto3" json:"balance,omitempty"`
	BalanceCash    float64                `protobuf:"fixed64,15,opt,name=balance_cash,json=balanceCash,proto3" json:"balance_cash,omitempty"`
	BalanceBonus   float64                `protobuf:"fixed64,16,opt,name=balance_bonus,json=balanceBonus,proto3" json:"balance_bonus,omitempty"`
	Hash           string                 `protobuf:"bytes,17,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordItem) Reset() {
	*x = RecordItem{}
	mi := &file_datacenter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordItem) ProtoMessage() {}

func (x *RecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordItem.ProtoReflect.Descriptor instead.
func (*RecordItem) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{15}
}

func (x *RecordItem) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *RecordItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordItem) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *RecordItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RecordItem) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *RecordItem) GetBaseBet() float64 {
	if x != nil {
		return x.BaseBet
	}
	return 0
}

func (x *RecordItem) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *RecordItem) GetRtp() float64 {
	if x != nil {
		return x.Rtp
	}
	return 0
}

func (x *RecordItem) GetPlayedDate() int64 {
	if x != nil {
		return x.PlayedDate
	}
	return 0
}

func (x *RecordItem) GetRoundID() string {
	if x != nil {
		return x.RoundID
	}
	return ""
}

func (x *RecordItem) GetInit() string {
	if x != nil {
		return x.Init
	}
	return ""
}

func (x *RecordItem) GetLog() []*RecordLog {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *RecordItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RecordItem) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *RecordItem) GetBalanceCash() float64 {
	if x != nil {
		return x.BalanceCash
	}
	return 0
}

func (x *RecordItem) GetBalanceBonus() float64 {
	if x != nil {
		return x.BalanceBonus
	}
	return 0
}

func (x *RecordItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetRecordsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Data          []*RecordItem          `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsResp) Reset() {
	*x = GetRecordsResp{}
	mi := &file_datacenter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsResp) ProtoMessage() {}

func (x *GetRecordsResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsResp.ProtoReflect.Descriptor instead.
func (*GetRecordsResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{16}
}

func (x *GetRecordsResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetRecordsResp) GetData() []*RecordItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type RecordLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cr            string                 `protobuf:"bytes,1,opt,name=cr,proto3" json:"cr,omitempty"`
	Sr            string                 `protobuf:"bytes,2,opt,name=sr,proto3" json:"sr,omitempty"`
	RoundId       string                 `protobuf:"bytes,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLog) Reset() {
	*x = RecordLog{}
	mi := &file_datacenter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLog) ProtoMessage() {}

func (x *RecordLog) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLog.ProtoReflect.Descriptor instead.
func (*RecordLog) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{17}
}

func (x *RecordLog) GetCr() string {
	if x != nil {
		return x.Cr
	}
	return ""
}

func (x *RecordLog) GetSr() string {
	if x != nil {
		return x.Sr
	}
	return ""
}

func (x *RecordLog) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type GetPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Factory       uint32                 `protobuf:"varint,2,opt,name=Factory,proto3" json:"Factory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerReq) Reset() {
	*x = GetPlayerReq{}
	mi := &file_datacenter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerReq) ProtoMessage() {}

func (x *GetPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerReq.ProtoReflect.Descriptor instead.
func (*GetPlayerReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlayerReq) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GetPlayerReq) GetFactory() uint32 {
	if x != nil {
		return x.Factory
	}
	return 0
}

type GetPlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HumanPlayer   *HumanPlayer           `protobuf:"bytes,1,opt,name=HumanPlayer,proto3" json:"HumanPlayer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResp) Reset() {
	*x = GetPlayerResp{}
	mi := &file_datacenter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResp) ProtoMessage() {}

func (x *GetPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResp.ProtoReflect.Descriptor instead.
func (*GetPlayerResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{19}
}

func (x *GetPlayerResp) GetHumanPlayer() *HumanPlayer {
	if x != nil {
		return x.HumanPlayer
	}
	return nil
}

type GetValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TimeOut       int64                  `protobuf:"varint,2,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueReq) Reset() {
	*x = GetValueReq{}
	mi := &file_datacenter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueReq) ProtoMessage() {}

func (x *GetValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueReq.ProtoReflect.Descriptor instead.
func (*GetValueReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{20}
}

func (x *GetValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetValueReq) GetTimeOut() int64 {
	if x != nil {
		return x.TimeOut
	}
	return 0
}

type GetValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResp) Reset() {
	*x = GetValueResp{}
	mi := &file_datacenter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResp) ProtoMessage() {}

func (x *GetValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResp.ProtoReflect.Descriptor instead.
func (*GetValueResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{21}
}

func (x *GetValueResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetValueResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimeOut       int32                  `protobuf:"varint,3,opt,name=time_out,json=timeOut,proto3" json:"time_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueReq) Reset() {
	*x = SetValueReq{}
	mi := &file_datacenter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueReq) ProtoMessage() {}

func (x *SetValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueReq.ProtoReflect.Descriptor instead.
func (*SetValueReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{22}
}

func (x *SetValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetValueReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetValueReq) GetTimeOut() int32 {
	if x != nil {
		return x.TimeOut
	}
	return 0
}

type SetValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResp) Reset() {
	*x = SetValueResp{}
	mi := &file_datacenter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResp) ProtoMessage() {}

func (x *SetValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResp.ProtoReflect.Descriptor instead.
func (*SetValueResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{23}
}

func (x *SetValueResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type UpdatePlayerAvatarAndGenderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Gender        uint32                 `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Factory       uint32                 `protobuf:"varint,4,opt,name=Factory,proto3" json:"Factory,omitempty"`
	HeadFrame     string                 `protobuf:"bytes,5,opt,name=head_frame,json=headFrame,proto3" json:"head_frame,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"` //昵称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerAvatarAndGenderReq) Reset() {
	*x = UpdatePlayerAvatarAndGenderReq{}
	mi := &file_datacenter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerAvatarAndGenderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerAvatarAndGenderReq) ProtoMessage() {}

func (x *UpdatePlayerAvatarAndGenderReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerAvatarAndGenderReq.ProtoReflect.Descriptor instead.
func (*UpdatePlayerAvatarAndGenderReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{24}
}

func (x *UpdatePlayerAvatarAndGenderReq) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *UpdatePlayerAvatarAndGenderReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdatePlayerAvatarAndGenderReq) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdatePlayerAvatarAndGenderReq) GetFactory() uint32 {
	if x != nil {
		return x.Factory
	}
	return 0
}

func (x *UpdatePlayerAvatarAndGenderReq) GetHeadFrame() string {
	if x != nil {
		return x.HeadFrame
	}
	return ""
}

func (x *UpdatePlayerAvatarAndGenderReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdatePlayerAvatarAndGenderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerAvatarAndGenderResp) Reset() {
	*x = UpdatePlayerAvatarAndGenderResp{}
	mi := &file_datacenter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerAvatarAndGenderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerAvatarAndGenderResp) ProtoMessage() {}

func (x *UpdatePlayerAvatarAndGenderResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerAvatarAndGenderResp.ProtoReflect.Descriptor instead.
func (*UpdatePlayerAvatarAndGenderResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{25}
}

type GetGameListResp_GameInfoItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏标志
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 游戏状态 1 正常 2 维护
	State         int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListResp_GameInfoItem) Reset() {
	*x = GetGameListResp_GameInfoItem{}
	mi := &file_datacenter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListResp_GameInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResp_GameInfoItem) ProtoMessage() {}

func (x *GetGameListResp_GameInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResp_GameInfoItem.ProtoReflect.Descriptor instead.
func (*GetGameListResp_GameInfoItem) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetGameListResp_GameInfoItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetGameListResp_GameInfoItem) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_datacenter_proto protoreflect.FileDescriptor

const file_datacenter_proto_rawDesc = "" +
	"\n" +
	"\x10datacenter.proto\x12\n" +
	"datacenter\x1a\fplayer.proto\x1a\n" +
	"base.proto\";\n" +
	"\rGetSessionReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\atimeOut\x18\x02 \x01(\x03R\atimeOut\"L\n" +
	"\x0eGetSessionResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\\\n" +
	"\x18SaveHashLotteryResultReq\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\x05R\x06gameId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"A\n" +
	"\x19SaveHashLotteryResultResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\"E\n" +
	"\x17GetHashLotteryResultReq\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\x05R\x06gameId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\"R\n" +
	"\x18GetHashLotteryResultResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03str\x18\x02 \x01(\tR\x03str\"e\n" +
	"\x15GetGameRecordsListReq\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\x05R\x06gameId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tisWinGold\x18\x03 \x01(\bR\tisWinGold\"X\n" +
	"\x16GetGameRecordsListResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\arecords\x18\x02 \x03(\tR\arecords\"\x10\n" +
	"\x0eGetGameListReq\"\xf3\x01\n" +
	"\x0fGetGameListResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03hot\x18\x02 \x03(\tR\x03hot\x12\x10\n" +
	"\x03new\x18\x03 \x03(\tR\x03new\x12\x1c\n" +
	"\trecommend\x18\x04 \x03(\tR\trecommend\x12:\n" +
	"\x03all\x18\x05 \x03(\v2(.datacenter.GetGameListResp.GameInfoItemR\x03all\x1a<\n" +
	"\fGameInfoItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\"%\n" +
	"\vUserLockReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\"&\n" +
	"\fUserLockResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"=\n" +
	"\rUserUnLockReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"(\n" +
	"\x0eUserUnLockResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"S\n" +
	"\rGetRecordsReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x12\n" +
	"\x04Hash\x18\x03 \x01(\tR\x04Hash\"\xd8\x03\n" +
	"\n" +
	"RecordItem\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\rR\aagentId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12\x10\n" +
	"\x03bet\x18\x03 \x01(\x01R\x03bet\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12&\n" +
	"\x0ecurrencySymbol\x18\x05 \x01(\tR\x0ecurrencySymbol\x12\x19\n" +
	"\bbase_bet\x18\x06 \x01(\x01R\abaseBet\x12\x10\n" +
	"\x03win\x18\a \x01(\x01R\x03win\x12\x10\n" +
	"\x03rtp\x18\b \x01(\x01R\x03rtp\x12\x1e\n" +
	"\n" +
	"playedDate\x18\t \x01(\x03R\n" +
	"playedDate\x12\x18\n" +
	"\aroundID\x18\n" +
	" \x01(\tR\aroundID\x12\x12\n" +
	"\x04init\x18\v \x01(\tR\x04init\x12'\n" +
	"\x03log\x18\f \x03(\v2\x15.datacenter.RecordLogR\x03log\x12\x16\n" +
	"\x06symbol\x18\r \x01(\tR\x06symbol\x12\x18\n" +
	"\abalance\x18\x0e \x01(\x01R\abalance\x12!\n" +
	"\fbalance_cash\x18\x0f \x01(\x01R\vbalanceCash\x12#\n" +
	"\rbalance_bonus\x18\x10 \x01(\x01R\fbalanceBonus\x12\x12\n" +
	"\x04hash\x18\x11 \x01(\tR\x04hash\"b\n" +
	"\x0eGetRecordsResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.datacenter.RecordItemR\x04data\"E\n" +
	"\tRecordLog\x12\x0e\n" +
	"\x02cr\x18\x01 \x01(\tR\x02cr\x12\x0e\n" +
	"\x02sr\x18\x02 \x01(\tR\x02sr\x12\x18\n" +
	"\aroundId\x18\x03 \x01(\tR\aroundId\"D\n" +
	"\fGetPlayerReq\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\rR\bPlayerId\x12\x18\n" +
	"\aFactory\x18\x02 \x01(\rR\aFactory\"F\n" +
	"\rGetPlayerResp\x125\n" +
	"\vHumanPlayer\x18\x01 \x01(\v2\x13.player.HumanPlayerR\vHumanPlayer\"9\n" +
	"\vGetValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\atimeOut\x18\x02 \x01(\x03R\atimeOut\"J\n" +
	"\fGetValueResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"P\n" +
	"\vSetValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x19\n" +
	"\btime_out\x18\x03 \x01(\x05R\atimeOut\"4\n" +
	"\fSetValueResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\"\xb9\x01\n" +
	"\x1eUpdatePlayerAvatarAndGenderReq\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\rR\bPlayerId\x12\x16\n" +
	"\x06Avatar\x18\x02 \x01(\tR\x06Avatar\x12\x16\n" +
	"\x06Gender\x18\x03 \x01(\rR\x06Gender\x12\x18\n" +
	"\aFactory\x18\x04 \x01(\rR\aFactory\x12\x1d\n" +
	"\n" +
	"head_frame\x18\x05 \x01(\tR\theadFrame\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"!\n" +
	"\x1fUpdatePlayerAvatarAndGenderResp2\xc6\a\n" +
	"\x11DataCenterService\x12@\n" +
	"\tGetPlayer\x12\x18.datacenter.GetPlayerReq\x1a\x19.datacenter.GetPlayerResp\x12=\n" +
	"\bGetValue\x12\x17.datacenter.GetValueReq\x1a\x18.datacenter.GetValueResp\x12=\n" +
	"\bSetValue\x12\x17.datacenter.SetValueReq\x1a\x18.datacenter.SetValueResp\x12v\n" +
	"\x1bUpdatePlayerAvatarAndGender\x12*.datacenter.UpdatePlayerAvatarAndGenderReq\x1a+.datacenter.UpdatePlayerAvatarAndGenderResp\x12C\n" +
	"\n" +
	"GetRecords\x12\x19.datacenter.GetRecordsReq\x1a\x1a.datacenter.GetRecordsResp\x12F\n" +
	"\vGetGameList\x12\x1a.datacenter.GetGameListReq\x1a\x1b.datacenter.GetGameListResp\x12=\n" +
	"\bUserLock\x12\x17.datacenter.UserLockReq\x1a\x18.datacenter.UserLockResp\x12C\n" +
	"\n" +
	"UserUnLock\x12\x19.datacenter.UserUnLockReq\x1a\x1a.datacenter.UserUnLockResp\x12B\n" +
	"\tGetSesson\x12\x19.datacenter.GetSessionReq\x1a\x1a.datacenter.GetSessionResp\x12d\n" +
	"\x15SaveHashLotteryResult\x12$.datacenter.SaveHashLotteryResultReq\x1a%.datacenter.SaveHashLotteryResultResp\x12a\n" +
	"\x14GetHashLotteryResult\x12#.datacenter.GetHashLotteryResultReq\x1a$.datacenter.GetHashLotteryResultResp\x12[\n" +
	"\x12GetGameRecordsList\x12!.datacenter.GetGameRecordsListReq\x1a\".datacenter.GetGameRecordsListRespB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_datacenter_proto_rawDescOnce sync.Once
	file_datacenter_proto_rawDescData []byte
)

func file_datacenter_proto_rawDescGZIP() []byte {
	file_datacenter_proto_rawDescOnce.Do(func() {
		file_datacenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datacenter_proto_rawDesc), len(file_datacenter_proto_rawDesc)))
	})
	return file_datacenter_proto_rawDescData
}

var file_datacenter_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_datacenter_proto_goTypes = []any{
	(*GetSessionReq)(nil),                   // 0: datacenter.GetSessionReq
	(*GetSessionResp)(nil),                  // 1: datacenter.GetSessionResp
	(*SaveHashLotteryResultReq)(nil),        // 2: datacenter.SaveHashLotteryResultReq
	(*SaveHashLotteryResultResp)(nil),       // 3: datacenter.SaveHashLotteryResultResp
	(*GetHashLotteryResultReq)(nil),         // 4: datacenter.GetHashLotteryResultReq
	(*GetHashLotteryResultResp)(nil),        // 5: datacenter.GetHashLotteryResultResp
	(*GetGameRecordsListReq)(nil),           // 6: datacenter.GetGameRecordsListReq
	(*GetGameRecordsListResp)(nil),          // 7: datacenter.GetGameRecordsListResp
	(*GetGameListReq)(nil),                  // 8: datacenter.GetGameListReq
	(*GetGameListResp)(nil),                 // 9: datacenter.GetGameListResp
	(*UserLockReq)(nil),                     // 10: datacenter.UserLockReq
	(*UserLockResp)(nil),                    // 11: datacenter.UserLockResp
	(*UserUnLockReq)(nil),                   // 12: datacenter.UserUnLockReq
	(*UserUnLockResp)(nil),                  // 13: datacenter.UserUnLockResp
	(*GetRecordsReq)(nil),                   // 14: datacenter.GetRecordsReq
	(*RecordItem)(nil),                      // 15: datacenter.RecordItem
	(*GetRecordsResp)(nil),                  // 16: datacenter.GetRecordsResp
	(*RecordLog)(nil),                       // 17: datacenter.RecordLog
	(*GetPlayerReq)(nil),                    // 18: datacenter.GetPlayerReq
	(*GetPlayerResp)(nil),                   // 19: datacenter.GetPlayerResp
	(*GetValueReq)(nil),                     // 20: datacenter.GetValueReq
	(*GetValueResp)(nil),                    // 21: datacenter.GetValueResp
	(*SetValueReq)(nil),                     // 22: datacenter.SetValueReq
	(*SetValueResp)(nil),                    // 23: datacenter.SetValueResp
	(*UpdatePlayerAvatarAndGenderReq)(nil),  // 24: datacenter.UpdatePlayerAvatarAndGenderReq
	(*UpdatePlayerAvatarAndGenderResp)(nil), // 25: datacenter.UpdatePlayerAvatarAndGenderResp
	(*GetGameListResp_GameInfoItem)(nil),    // 26: datacenter.GetGameListResp.GameInfoItem
	(ErrorCode)(0),                          // 27: base.error_code
	(*HumanPlayer)(nil),                     // 28: player.HumanPlayer
}
var file_datacenter_proto_depIdxs = []int32{
	27, // 0: datacenter.GetSessionResp.code:type_name -> base.error_code
	27, // 1: datacenter.SaveHashLotteryResultResp.code:type_name -> base.error_code
	27, // 2: datacenter.GetHashLotteryResultResp.code:type_name -> base.error_code
	27, // 3: datacenter.GetGameRecordsListResp.code:type_name -> base.error_code
	27, // 4: datacenter.GetGameListResp.code:type_name -> base.error_code
	26, // 5: datacenter.GetGameListResp.all:type_name -> datacenter.GetGameListResp.GameInfoItem
	17, // 6: datacenter.RecordItem.log:type_name -> datacenter.RecordLog
	27, // 7: datacenter.GetRecordsResp.code:type_name -> base.error_code
	15, // 8: datacenter.GetRecordsResp.data:type_name -> datacenter.RecordItem
	28, // 9: datacenter.GetPlayerResp.HumanPlayer:type_name -> player.HumanPlayer
	27, // 10: datacenter.GetValueResp.code:type_name -> base.error_code
	27, // 11: datacenter.SetValueResp.code:type_name -> base.error_code
	18, // 12: datacenter.DataCenterService.GetPlayer:input_type -> datacenter.GetPlayerReq
	20, // 13: datacenter.DataCenterService.GetValue:input_type -> datacenter.GetValueReq
	22, // 14: datacenter.DataCenterService.SetValue:input_type -> datacenter.SetValueReq
	24, // 15: datacenter.DataCenterService.UpdatePlayerAvatarAndGender:input_type -> datacenter.UpdatePlayerAvatarAndGenderReq
	14, // 16: datacenter.DataCenterService.GetRecords:input_type -> datacenter.GetRecordsReq
	8,  // 17: datacenter.DataCenterService.GetGameList:input_type -> datacenter.GetGameListReq
	10, // 18: datacenter.DataCenterService.UserLock:input_type -> datacenter.UserLockReq
	12, // 19: datacenter.DataCenterService.UserUnLock:input_type -> datacenter.UserUnLockReq
	0,  // 20: datacenter.DataCenterService.GetSesson:input_type -> datacenter.GetSessionReq
	2,  // 21: datacenter.DataCenterService.SaveHashLotteryResult:input_type -> datacenter.SaveHashLotteryResultReq
	4,  // 22: datacenter.DataCenterService.GetHashLotteryResult:input_type -> datacenter.GetHashLotteryResultReq
	6,  // 23: datacenter.DataCenterService.GetGameRecordsList:input_type -> datacenter.GetGameRecordsListReq
	19, // 24: datacenter.DataCenterService.GetPlayer:output_type -> datacenter.GetPlayerResp
	21, // 25: datacenter.DataCenterService.GetValue:output_type -> datacenter.GetValueResp
	23, // 26: datacenter.DataCenterService.SetValue:output_type -> datacenter.SetValueResp
	25, // 27: datacenter.DataCenterService.UpdatePlayerAvatarAndGender:output_type -> datacenter.UpdatePlayerAvatarAndGenderResp
	16, // 28: datacenter.DataCenterService.GetRecords:output_type -> datacenter.GetRecordsResp
	9,  // 29: datacenter.DataCenterService.GetGameList:output_type -> datacenter.GetGameListResp
	11, // 30: datacenter.DataCenterService.UserLock:output_type -> datacenter.UserLockResp
	13, // 31: datacenter.DataCenterService.UserUnLock:output_type -> datacenter.UserUnLockResp
	1,  // 32: datacenter.DataCenterService.GetSesson:output_type -> datacenter.GetSessionResp
	3,  // 33: datacenter.DataCenterService.SaveHashLotteryResult:output_type -> datacenter.SaveHashLotteryResultResp
	5,  // 34: datacenter.DataCenterService.GetHashLotteryResult:output_type -> datacenter.GetHashLotteryResultResp
	7,  // 35: datacenter.DataCenterService.GetGameRecordsList:output_type -> datacenter.GetGameRecordsListResp
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_datacenter_proto_init() }
func file_datacenter_proto_init() {
	if File_datacenter_proto != nil {
		return
	}
	file_player_proto_init()
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datacenter_proto_rawDesc), len(file_datacenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datacenter_proto_goTypes,
		DependencyIndexes: file_datacenter_proto_depIdxs,
		MessageInfos:      file_datacenter_proto_msgTypes,
	}.Build()
	File_datacenter_proto = out.File
	file_datacenter_proto_goTypes = nil
	file_datacenter_proto_depIdxs = nil
}
