// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: lottery.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单笔下注。金额使用玩家币种的十进制字符串，最多保留两位小数。
type BetItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本局内唯一的下注编号，也是单笔下注的幂等键。
	BetId string `protobuf:"bytes,1,opt,name=betId,proto3" json:"betId,omitempty"`
	// 真人玩家编号。
	UserId uint32 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 玩家账户币种；奖池入账前会按汇率换算为 CNY。
	CurrencyType string `protobuf:"bytes,3,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 实际扣除的玩家余额。
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 可选的下注区域或玩法标识。
	AreaId        string `protobuf:"bytes,5,opt,name=areaId,proto3" json:"areaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetItem) Reset() {
	*x = BetItem{}
	mi := &file_lottery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetItem) ProtoMessage() {}

func (x *BetItem) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetItem.ProtoReflect.Descriptor instead.
func (*BetItem) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{0}
}

func (x *BetItem) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *BetItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BetItem) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *BetItem) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BetItem) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

// 一次下注请求可以包含本局一个或多个真人玩家的下注。
type BetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本次 RPC 请求编号，用于审计和问题追踪。
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// 牌局唯一编号。
	RoundId string `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	// 游戏编号。
	GameId uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	// 代理编号。
	Agent uint32 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	// 房间等级；参与奖池二级键 agentId_symbol_level 的路由。
	Level uint32 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	// 本次提交的下注列表；批量请求按项返回结果，不回滚已成功项。
	Items         []*BetItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetRequest) Reset() {
	*x = BetRequest{}
	mi := &file_lottery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetRequest) ProtoMessage() {}

func (x *BetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetRequest.ProtoReflect.Descriptor instead.
func (*BetRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{1}
}

func (x *BetRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BetRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BetRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *BetRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *BetRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BetRequest) GetItems() []*BetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单笔下注处理结果。
type BetItemResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	BetId  string                 `protobuf:"bytes,1,opt,name=betId,proto3" json:"betId,omitempty"`
	UserId uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 该下注的业务错误码。
	Code ErrorCode `protobuf:"varint,3,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	// true 表示已扣款并计入本局下注摘要。
	Accepted bool `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// 扣款后的玩家余额。
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// 失败原因说明，成功时为空。
	Message       string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetItemResult) Reset() {
	*x = BetItemResult{}
	mi := &file_lottery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetItemResult) ProtoMessage() {}

func (x *BetItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetItemResult.ProtoReflect.Descriptor instead.
func (*BetItemResult) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{2}
}

func (x *BetItemResult) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *BetItemResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BetItemResult) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *BetItemResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BetItemResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BetItemResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 下注响应。
type BetResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	RoundId string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	// 当前资金状态，下注阶段通常为 BETTING。
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// 本局全部已接受下注的 SHA-256 摘要。
	BetDigest     string           `protobuf:"bytes,4,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	Items         []*BetItemResult `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetResponse) Reset() {
	*x = BetResponse{}
	mi := &file_lottery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetResponse) ProtoMessage() {}

func (x *BetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetResponse.ProtoReflect.Descriptor instead.
func (*BetResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{3}
}

func (x *BetResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *BetResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BetResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BetResponse) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *BetResponse) GetItems() []*BetItemResult {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单个真人玩家的候选赔付。
type PrePayItem struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CurrencyType string                 `protobuf:"bytes,2,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 实际返还玩家的总金额，不是净利润。
	Payout        string `protobuf:"bytes,3,opt,name=payout,proto3" json:"payout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePayItem) Reset() {
	*x = PrePayItem{}
	mi := &file_lottery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayItem) ProtoMessage() {}

func (x *PrePayItem) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayItem.ProtoReflect.Descriptor instead.
func (*PrePayItem) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{4}
}

func (x *PrePayItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PrePayItem) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *PrePayItem) GetPayout() string {
	if x != nil {
		return x.Payout
	}
	return ""
}

// 赔付预留请求，必须覆盖本局全部有效真人玩家。
type PrePayRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RoundId   string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameId    uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Agent     uint32                 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Level     uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	// 必须与资金服务按已接受下注计算出的摘要完全一致。
	BetDigest string `protobuf:"bytes,6,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	// 完整候选游戏结果的摘要。
	OutcomeHash string `protobuf:"bytes,7,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	// 预留有效秒数；传 0 使用服务默认值 300 秒。
	TimeoutSeconds uint32        `protobuf:"varint,8,opt,name=timeoutSeconds,proto3" json:"timeoutSeconds,omitempty"`
	Items          []*PrePayItem `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrePayRequest) Reset() {
	*x = PrePayRequest{}
	mi := &file_lottery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayRequest) ProtoMessage() {}

func (x *PrePayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayRequest.ProtoReflect.Descriptor instead.
func (*PrePayRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{5}
}

func (x *PrePayRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PrePayRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *PrePayRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *PrePayRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *PrePayRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PrePayRequest) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *PrePayRequest) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *PrePayRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *PrePayRequest) GetItems() []*PrePayItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 赔付预留响应。
type PrePayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	// true 表示本次赔付预留成功。
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RoundId string `protobuf:"bytes,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
	State   string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// 本次预留的唯一编号。
	ReservationId string `protobuf:"bytes,5,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	// 按汇率换算后的 CNY 预留总额。
	TotalPayoutCny string `protobuf:"bytes,6,opt,name=totalPayoutCny,proto3" json:"totalPayoutCny,omitempty"`
	// Unix 秒级过期时间。
	ExpiresAt int64 `protobuf:"varint,7,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	// INVALID_REQUEST、BET_MISMATCH、ROUND_CONFLICT 或 INSUFFICIENT_POOL。
	Reason        string `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	BetDigest     string `protobuf:"bytes,9,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	OutcomeHash   string `protobuf:"bytes,10,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePayResponse) Reset() {
	*x = PrePayResponse{}
	mi := &file_lottery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayResponse) ProtoMessage() {}

func (x *PrePayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayResponse.ProtoReflect.Descriptor instead.
func (*PrePayResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{6}
}

func (x *PrePayResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *PrePayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrePayResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *PrePayResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PrePayResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PrePayResponse) GetTotalPayoutCny() string {
	if x != nil {
		return x.TotalPayoutCny
	}
	return ""
}

func (x *PrePayResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *PrePayResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PrePayResponse) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *PrePayResponse) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

// 单个真人玩家的结算数据。
type SettlementItem struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CurrencyType string                 `protobuf:"bytes,2,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 本局该玩家全部已接受下注的汇总金额。
	BetAmount string `protobuf:"bytes,3,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	// 实际返还玩家账户的金额；玩家输时也必须提交 0。
	Payout string `protobuf:"bytes,4,opt,name=payout,proto3" json:"payout,omitempty"`
	// 玩家净利润，必须等于 payout - betAmount，允许为负数。
	Profit string `protobuf:"bytes,5,opt,name=profit,proto3" json:"profit,omitempty"`
	// 游戏侧提供的完整注单详情。
	Record        string `protobuf:"bytes,6,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementItem) Reset() {
	*x = SettlementItem{}
	mi := &file_lottery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementItem) ProtoMessage() {}

func (x *SettlementItem) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementItem.ProtoReflect.Descriptor instead.
func (*SettlementItem) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{7}
}

func (x *SettlementItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SettlementItem) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *SettlementItem) GetBetAmount() string {
	if x != nil {
		return x.BetAmount
	}
	return ""
}

func (x *SettlementItem) GetPayout() string {
	if x != nil {
		return x.Payout
	}
	return ""
}

func (x *SettlementItem) GetProfit() string {
	if x != nil {
		return x.Profit
	}
	return ""
}

func (x *SettlementItem) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

// 批量结算请求，必须覆盖本局全部有效真人玩家且不能重复。
type SettlementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全局唯一结算编号，也是结算幂等键。
	SettlementId  string `protobuf:"bytes,1,opt,name=settlementId,proto3" json:"settlementId,omitempty"`
	RoundId       string `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameId        uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Agent         uint32 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Level         uint32 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	ReservationId string `protobuf:"bytes,6,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	BetDigest     string `protobuf:"bytes,7,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	OutcomeHash   string `protobuf:"bytes,8,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	// NORMAL 为正常赔付，VOID_REFUND 为全额退回下注并关闭本局。
	Mode          string            `protobuf:"bytes,9,opt,name=mode,proto3" json:"mode,omitempty"`
	Items         []*SettlementItem `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementRequest) Reset() {
	*x = SettlementRequest{}
	mi := &file_lottery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementRequest) ProtoMessage() {}

func (x *SettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementRequest.ProtoReflect.Descriptor instead.
func (*SettlementRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{8}
}

func (x *SettlementRequest) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *SettlementRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SettlementRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SettlementRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *SettlementRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SettlementRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *SettlementRequest) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *SettlementRequest) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *SettlementRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SettlementRequest) GetItems() []*SettlementItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单个玩家的结算结果。
type SettlementItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Code          ErrorCode              `protobuf:"varint,2,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementItemResult) Reset() {
	*x = SettlementItemResult{}
	mi := &file_lottery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementItemResult) ProtoMessage() {}

func (x *SettlementItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementItemResult.ProtoReflect.Descriptor instead.
func (*SettlementItemResult) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{9}
}

func (x *SettlementItemResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SettlementItemResult) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *SettlementItemResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SettlementItemResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 批量结算响应。
type SettlementResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          ErrorCode               `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	RoundId       string                  `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	State         string                  `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	SettlementId  string                  `protobuf:"bytes,4,opt,name=settlementId,proto3" json:"settlementId,omitempty"`
	Items         []*SettlementItemResult `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementResponse) Reset() {
	*x = SettlementResponse{}
	mi := &file_lottery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResponse) ProtoMessage() {}

func (x *SettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResponse.ProtoReflect.Descriptor instead.
func (*SettlementResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{10}
}

func (x *SettlementResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *SettlementResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SettlementResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SettlementResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *SettlementResponse) GetItems() []*SettlementItemResult {
	if x != nil {
		return x.Items
	}
	return nil
}

// 按牌局编号查询资金状态。
type GetRoundFinanceStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoundFinanceStateReq) Reset() {
	*x = GetRoundFinanceStateReq{}
	mi := &file_lottery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundFinanceStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundFinanceStateReq) ProtoMessage() {}

func (x *GetRoundFinanceStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundFinanceStateReq.ProtoReflect.Descriptor instead.
func (*GetRoundFinanceStateReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoundFinanceStateReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

// 牌局资金状态快照。
type GetRoundFinanceStateResp struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	RoundId string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	// BETTING、RESERVED、SETTLED、VOIDED 或 EXPIRED。
	State         string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	BetDigest     string `protobuf:"bytes,4,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	ReservationId string `protobuf:"bytes,5,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	OutcomeHash   string `protobuf:"bytes,6,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	ExpiresAt     int64  `protobuf:"varint,7,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	SettlementId  string `protobuf:"bytes,8,opt,name=settlementId,proto3" json:"settlementId,omitempty"`
	// 本局全部已接受下注换算后的 CNY 总额。
	TotalBetCny string `protobuf:"bytes,9,opt,name=totalBetCny,proto3" json:"totalBetCny,omitempty"`
	// 当前预留记录的 CNY 金额。
	TotalReservedCny string `protobuf:"bytes,10,opt,name=totalReservedCny,proto3" json:"totalReservedCny,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRoundFinanceStateResp) Reset() {
	*x = GetRoundFinanceStateResp{}
	mi := &file_lottery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundFinanceStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundFinanceStateResp) ProtoMessage() {}

func (x *GetRoundFinanceStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundFinanceStateResp.ProtoReflect.Descriptor instead.
func (*GetRoundFinanceStateResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoundFinanceStateResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetRoundFinanceStateResp) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetRoundFinanceStateResp) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetTotalBetCny() string {
	if x != nil {
		return x.TotalBetCny
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetTotalReservedCny() string {
	if x != nil {
		return x.TotalReservedCny
	}
	return ""
}

var File_lottery_proto protoreflect.FileDescriptor

const file_lottery_proto_rawDesc = "" +
	"\n" +
	"\rlottery.proto\x12\alottery\x1a\n" +
	"base.proto\"\x8b\x01\n" +
	"\aBetItem\x12\x14\n" +
	"\x05betId\x18\x01 \x01(\tR\x05betId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12\"\n" +
	"\fcurrencyType\x18\x03 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x16\n" +
	"\x06areaId\x18\x05 \x01(\tR\x06areaId\"\xbc\x01\n" +
	"\n" +
	"BetRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12&\n" +
	"\x05items\x18\b \x03(\v2\x10.lottery.BetItemR\x05itemsJ\x04\b\x06\x10\aJ\x04\b\a\x10\b\"\xb5\x01\n" +
	"\rBetItemResult\x12\x14\n" +
	"\x05betId\x18\x01 \x01(\tR\x05betId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12$\n" +
	"\x04code\x18\x03 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xaf\x01\n" +
	"\vBetResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tbetDigest\x18\x04 \x01(\tR\tbetDigest\x12,\n" +
	"\x05items\x18\x05 \x03(\v2\x16.lottery.BetItemResultR\x05items\"`\n" +
	"\n" +
	"PrePayItem\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\fcurrencyType\x18\x02 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06payout\x18\x03 \x01(\tR\x06payout\"\x9e\x02\n" +
	"\rPrePayRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x1c\n" +
	"\tbetDigest\x18\x06 \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\a \x01(\tR\voutcomeHash\x12&\n" +
	"\x0etimeoutSeconds\x18\b \x01(\rR\x0etimeoutSeconds\x12)\n" +
	"\x05items\x18\t \x03(\v2\x13.lottery.PrePayItemR\x05items\"\xc4\x02\n" +
	"\x0ePrePayResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\aroundId\x18\x03 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12$\n" +
	"\rreservationId\x18\x05 \x01(\tR\rreservationId\x12&\n" +
	"\x0etotalPayoutCny\x18\x06 \x01(\tR\x0etotalPayoutCny\x12\x1c\n" +
	"\texpiresAt\x18\a \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1c\n" +
	"\tbetDigest\x18\t \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\n" +
	" \x01(\tR\voutcomeHash\"\xb2\x01\n" +
	"\x0eSettlementItem\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\fcurrencyType\x18\x02 \x01(\tR\fcurrencyType\x12\x1c\n" +
	"\tbetAmount\x18\x03 \x01(\tR\tbetAmount\x12\x16\n" +
	"\x06payout\x18\x04 \x01(\tR\x06payout\x12\x16\n" +
	"\x06profit\x18\x05 \x01(\tR\x06profit\x12\x16\n" +
	"\x06record\x18\x06 \x01(\tR\x06record\"\xbe\x02\n" +
	"\x11SettlementRequest\x12\"\n" +
	"\fsettlementId\x18\x01 \x01(\tR\fsettlementId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12$\n" +
	"\rreservationId\x18\x06 \x01(\tR\rreservationId\x12\x1c\n" +
	"\tbetDigest\x18\a \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\b \x01(\tR\voutcomeHash\x12\x12\n" +
	"\x04mode\x18\t \x01(\tR\x04mode\x12-\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x17.lottery.SettlementItemR\x05items\"\x8a\x01\n" +
	"\x14SettlementItemResult\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12$\n" +
	"\x04code\x18\x02 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xc3\x01\n" +
	"\x12SettlementResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\"\n" +
	"\fsettlementId\x18\x04 \x01(\tR\fsettlementId\x123\n" +
	"\x05items\x18\x05 \x03(\v2\x1d.lottery.SettlementItemResultR\x05items\"3\n" +
	"\x17GetRoundFinanceStateReq\x12\x18\n" +
	"\aroundId\x18\x01 \x01(\tR\aroundId\"\xe6\x02\n" +
	"\x18GetRoundFinanceStateResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tbetDigest\x18\x04 \x01(\tR\tbetDigest\x12$\n" +
	"\rreservationId\x18\x05 \x01(\tR\rreservationId\x12 \n" +
	"\voutcomeHash\x18\x06 \x01(\tR\voutcomeHash\x12\x1c\n" +
	"\texpiresAt\x18\a \x01(\x03R\texpiresAt\x12\"\n" +
	"\fsettlementId\x18\b \x01(\tR\fsettlementId\x12 \n" +
	"\vtotalBetCny\x18\t \x01(\tR\vtotalBetCny\x12*\n" +
	"\x10totalReservedCny\x18\n" +
	" \x01(\tR\x10totalReservedCny2\xa1\x02\n" +
	"\x0eLotteryService\x120\n" +
	"\x03Bet\x12\x13.lottery.BetRequest\x1a\x14.lottery.BetResponse\x129\n" +
	"\x06PrePay\x12\x16.lottery.PrePayRequest\x1a\x17.lottery.PrePayResponse\x12E\n" +
	"\n" +
	"Settlement\x12\x1a.lottery.SettlementRequest\x1a\x1b.lottery.SettlementResponse\x12[\n" +
	"\x14GetRoundFinanceState\x12 .lottery.GetRoundFinanceStateReq\x1a!.lottery.GetRoundFinanceStateRespB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_lottery_proto_rawDescOnce sync.Once
	file_lottery_proto_rawDescData []byte
)

func file_lottery_proto_rawDescGZIP() []byte {
	file_lottery_proto_rawDescOnce.Do(func() {
		file_lottery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)))
	})
	return file_lottery_proto_rawDescData
}

var file_lottery_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lottery_proto_goTypes = []any{
	(*BetItem)(nil),                  // 0: lottery.BetItem
	(*BetRequest)(nil),               // 1: lottery.BetRequest
	(*BetItemResult)(nil),            // 2: lottery.BetItemResult
	(*BetResponse)(nil),              // 3: lottery.BetResponse
	(*PrePayItem)(nil),               // 4: lottery.PrePayItem
	(*PrePayRequest)(nil),            // 5: lottery.PrePayRequest
	(*PrePayResponse)(nil),           // 6: lottery.PrePayResponse
	(*SettlementItem)(nil),           // 7: lottery.SettlementItem
	(*SettlementRequest)(nil),        // 8: lottery.SettlementRequest
	(*SettlementItemResult)(nil),     // 9: lottery.SettlementItemResult
	(*SettlementResponse)(nil),       // 10: lottery.SettlementResponse
	(*GetRoundFinanceStateReq)(nil),  // 11: lottery.GetRoundFinanceStateReq
	(*GetRoundFinanceStateResp)(nil), // 12: lottery.GetRoundFinanceStateResp
	(ErrorCode)(0),                   // 13: base.error_code
}
var file_lottery_proto_depIdxs = []int32{
	0,  // 0: lottery.BetRequest.items:type_name -> lottery.BetItem
	13, // 1: lottery.BetItemResult.code:type_name -> base.error_code
	13, // 2: lottery.BetResponse.code:type_name -> base.error_code
	2,  // 3: lottery.BetResponse.items:type_name -> lottery.BetItemResult
	4,  // 4: lottery.PrePayRequest.items:type_name -> lottery.PrePayItem
	13, // 5: lottery.PrePayResponse.code:type_name -> base.error_code
	7,  // 6: lottery.SettlementRequest.items:type_name -> lottery.SettlementItem
	13, // 7: lottery.SettlementItemResult.code:type_name -> base.error_code
	13, // 8: lottery.SettlementResponse.code:type_name -> base.error_code
	9,  // 9: lottery.SettlementResponse.items:type_name -> lottery.SettlementItemResult
	13, // 10: lottery.GetRoundFinanceStateResp.code:type_name -> base.error_code
	1,  // 11: lottery.LotteryService.Bet:input_type -> lottery.BetRequest
	5,  // 12: lottery.LotteryService.PrePay:input_type -> lottery.PrePayRequest
	8,  // 13: lottery.LotteryService.Settlement:input_type -> lottery.SettlementRequest
	11, // 14: lottery.LotteryService.GetRoundFinanceState:input_type -> lottery.GetRoundFinanceStateReq
	3,  // 15: lottery.LotteryService.Bet:output_type -> lottery.BetResponse
	6,  // 16: lottery.LotteryService.PrePay:output_type -> lottery.PrePayResponse
	10, // 17: lottery.LotteryService.Settlement:output_type -> lottery.SettlementResponse
	12, // 18: lottery.LotteryService.GetRoundFinanceState:output_type -> lottery.GetRoundFinanceStateResp
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_lottery_proto_init() }
func file_lottery_proto_init() {
	if File_lottery_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lottery_proto_goTypes,
		DependencyIndexes: file_lottery_proto_depIdxs,
		MessageInfos:      file_lottery_proto_msgTypes,
	}.Build()
	File_lottery_proto = out.File
	file_lottery_proto_goTypes = nil
	file_lottery_proto_depIdxs = nil
}
