// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: lottery.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单笔下注。金额使用玩家币种的十进制字符串，最多保留两位小数。
type BetItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本局内唯一的下注编号，也是单笔下注的幂等键。
	BetId string `protobuf:"bytes,1,opt,name=betId,proto3" json:"betId,omitempty"`
	// 真人玩家编号。
	UserId uint32 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 玩家账户币种；奖池入账前会按汇率换算为 CNY。
	CurrencyType string `protobuf:"bytes,3,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 实际扣除的玩家余额。
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 可选的下注区域或玩法标识。
	AreaId        string `protobuf:"bytes,5,opt,name=areaId,proto3" json:"areaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetItem) Reset() {
	*x = BetItem{}
	mi := &file_lottery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetItem) ProtoMessage() {}

func (x *BetItem) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetItem.ProtoReflect.Descriptor instead.
func (*BetItem) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{0}
}

func (x *BetItem) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *BetItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BetItem) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *BetItem) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BetItem) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

// 一次下注请求可以包含本局一个或多个真人玩家的下注。
type BetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本次 RPC 请求编号，用于审计和问题追踪。
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// 牌局唯一编号。
	RoundId string `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	// 游戏编号。
	GameId uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	// 代理编号。
	Agent uint32 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	// 房间等级；参与奖池二级键 agentId_symbol_level 的路由。
	Level uint32 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	// 本次提交的下注列表；批量请求按项返回结果，不回滚已成功项。
	Items         []*BetItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetRequest) Reset() {
	*x = BetRequest{}
	mi := &file_lottery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetRequest) ProtoMessage() {}

func (x *BetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetRequest.ProtoReflect.Descriptor instead.
func (*BetRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{1}
}

func (x *BetRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BetRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BetRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *BetRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *BetRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BetRequest) GetItems() []*BetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单笔下注处理结果。
type BetItemResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	BetId  string                 `protobuf:"bytes,1,opt,name=betId,proto3" json:"betId,omitempty"`
	UserId uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 该下注的业务错误码。
	Code ErrorCode `protobuf:"varint,3,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	// true 表示已扣款并计入本局下注摘要。
	Accepted bool `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// 扣款后的玩家余额。
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// 失败原因说明，成功时为空。
	Message       string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetItemResult) Reset() {
	*x = BetItemResult{}
	mi := &file_lottery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetItemResult) ProtoMessage() {}

func (x *BetItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetItemResult.ProtoReflect.Descriptor instead.
func (*BetItemResult) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{2}
}

func (x *BetItemResult) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *BetItemResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BetItemResult) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *BetItemResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BetItemResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BetItemResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 下注响应。
type BetResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	RoundId string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	// 当前资金状态，下注阶段通常为 BETTING。
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// 本局全部已接受下注的 SHA-256 摘要。
	BetDigest     string           `protobuf:"bytes,4,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	Items         []*BetItemResult `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetResponse) Reset() {
	*x = BetResponse{}
	mi := &file_lottery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetResponse) ProtoMessage() {}

func (x *BetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetResponse.ProtoReflect.Descriptor instead.
func (*BetResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{3}
}

func (x *BetResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *BetResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BetResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BetResponse) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *BetResponse) GetItems() []*BetItemResult {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单个真人玩家的候选赔付。
type PrePayItem struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CurrencyType string                 `protobuf:"bytes,2,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 实际返还玩家的总金额，不是净利润。
	Payout        string `protobuf:"bytes,3,opt,name=payout,proto3" json:"payout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePayItem) Reset() {
	*x = PrePayItem{}
	mi := &file_lottery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayItem) ProtoMessage() {}

func (x *PrePayItem) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayItem.ProtoReflect.Descriptor instead.
func (*PrePayItem) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{4}
}

func (x *PrePayItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PrePayItem) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *PrePayItem) GetPayout() string {
	if x != nil {
		return x.Payout
	}
	return ""
}

// 赔付预留请求，必须覆盖本局全部有效真人玩家。
type PrePayRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RoundId   string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameId    uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Agent     uint32                 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Level     uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	// 必须与资金服务按已接受下注计算出的摘要完全一致。
	BetDigest string `protobuf:"bytes,6,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	// 完整候选游戏结果的摘要。
	OutcomeHash string `protobuf:"bytes,7,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	// 预留有效秒数；传 0 使用服务默认值 300 秒。
	TimeoutSeconds  uint32        `protobuf:"varint,8,opt,name=timeoutSeconds,proto3" json:"timeoutSeconds,omitempty"`
	Items           []*PrePayItem `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	ReservationMode string        `protobuf:"bytes,10,opt,name=reservationMode,proto3" json:"reservationMode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrePayRequest) Reset() {
	*x = PrePayRequest{}
	mi := &file_lottery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayRequest) ProtoMessage() {}

func (x *PrePayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayRequest.ProtoReflect.Descriptor instead.
func (*PrePayRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{5}
}

func (x *PrePayRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PrePayRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *PrePayRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *PrePayRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *PrePayRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PrePayRequest) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *PrePayRequest) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *PrePayRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *PrePayRequest) GetItems() []*PrePayItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PrePayRequest) GetReservationMode() string {
	if x != nil {
		return x.ReservationMode
	}
	return ""
}

// 赔付预留响应。
type PrePayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	// true 表示本次赔付预留成功。
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RoundId string `protobuf:"bytes,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
	State   string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// 本次预留的唯一编号。
	ReservationId string `protobuf:"bytes,5,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	// 按汇率换算后的 CNY 预留总额。
	TotalPayoutCny string `protobuf:"bytes,6,opt,name=totalPayoutCny,proto3" json:"totalPayoutCny,omitempty"`
	// Unix 秒级过期时间。
	ExpiresAt int64 `protobuf:"varint,7,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	// INVALID_REQUEST、BET_MISMATCH、ROUND_CONFLICT 或 INSUFFICIENT_POOL。
	Reason          string `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	BetDigest       string `protobuf:"bytes,9,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	OutcomeHash     string `protobuf:"bytes,10,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	ReservationMode string `protobuf:"bytes,11,opt,name=reservationMode,proto3" json:"reservationMode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrePayResponse) Reset() {
	*x = PrePayResponse{}
	mi := &file_lottery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayResponse) ProtoMessage() {}

func (x *PrePayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayResponse.ProtoReflect.Descriptor instead.
func (*PrePayResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{6}
}

func (x *PrePayResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *PrePayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrePayResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *PrePayResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PrePayResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PrePayResponse) GetTotalPayoutCny() string {
	if x != nil {
		return x.TotalPayoutCny
	}
	return ""
}

func (x *PrePayResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *PrePayResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PrePayResponse) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *PrePayResponse) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *PrePayResponse) GetReservationMode() string {
	if x != nil {
		return x.ReservationMode
	}
	return ""
}

// 延长预留有效期：只续命，不改金额/结果。
type RenewReservationRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RoundId   string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameId    uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Agent     uint32                 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Level     uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	// 必须与当前生效的 reservationId 一致。
	ReservationId string `protobuf:"bytes,6,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	// 可选一致性校验：非空时必须与当前预留一致。
	BetDigest   string `protobuf:"bytes,7,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	OutcomeHash string `protobuf:"bytes,8,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	// 从 now 起再保留的秒数；0 使用默认 60 秒。
	// 新 expiresAt = max(旧 expiresAt, now + extendSeconds)。
	ExtendSeconds uint32 `protobuf:"varint,9,opt,name=extendSeconds,proto3" json:"extendSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewReservationRequest) Reset() {
	*x = RenewReservationRequest{}
	mi := &file_lottery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewReservationRequest) ProtoMessage() {}

func (x *RenewReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewReservationRequest.ProtoReflect.Descriptor instead.
func (*RenewReservationRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{7}
}

func (x *RenewReservationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenewReservationRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RenewReservationRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RenewReservationRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *RenewReservationRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RenewReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RenewReservationRequest) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *RenewReservationRequest) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *RenewReservationRequest) GetExtendSeconds() uint32 {
	if x != nil {
		return x.ExtendSeconds
	}
	return 0
}

type RenewReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RoundId       string                 `protobuf:"bytes,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	ReservationId string                 `protobuf:"bytes,5,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	// INVALID_REQUEST / NOT_RESERVED / EXPIRED / ROUND_CONFLICT / BET_MISMATCH
	Reason          string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	BetDigest       string `protobuf:"bytes,8,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	OutcomeHash     string `protobuf:"bytes,9,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	ReservationMode string `protobuf:"bytes,10,opt,name=reservationMode,proto3" json:"reservationMode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenewReservationResponse) Reset() {
	*x = RenewReservationResponse{}
	mi := &file_lottery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewReservationResponse) ProtoMessage() {}

func (x *RenewReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewReservationResponse.ProtoReflect.Descriptor instead.
func (*RenewReservationResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{8}
}

func (x *RenewReservationResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *RenewReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenewReservationResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RenewReservationResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RenewReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RenewReservationResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RenewReservationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RenewReservationResponse) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *RenewReservationResponse) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *RenewReservationResponse) GetReservationMode() string {
	if x != nil {
		return x.ReservationMode
	}
	return ""
}

// 单个真人玩家的结算数据。
type SettlementItem struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CurrencyType string                 `protobuf:"bytes,2,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 本局该玩家全部已接受下注的汇总金额。
	BetAmount string `protobuf:"bytes,3,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	// 实际返还玩家账户的金额；玩家输时也必须提交 0。
	Payout string `protobuf:"bytes,4,opt,name=payout,proto3" json:"payout,omitempty"`
	// 玩家净利润，必须等于 payout - betAmount，允许为负数。
	Profit string `protobuf:"bytes,5,opt,name=profit,proto3" json:"profit,omitempty"`
	// 游戏侧提供的完整注单详情。
	Record string `protobuf:"bytes,6,opt,name=record,proto3" json:"record,omitempty"`
	// 游戏侧计算的抽水金额，使用玩家币种。
	Pump          string `protobuf:"bytes,7,opt,name=pump,proto3" json:"pump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementItem) Reset() {
	*x = SettlementItem{}
	mi := &file_lottery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementItem) ProtoMessage() {}

func (x *SettlementItem) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementItem.ProtoReflect.Descriptor instead.
func (*SettlementItem) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{9}
}

func (x *SettlementItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SettlementItem) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *SettlementItem) GetBetAmount() string {
	if x != nil {
		return x.BetAmount
	}
	return ""
}

func (x *SettlementItem) GetPayout() string {
	if x != nil {
		return x.Payout
	}
	return ""
}

func (x *SettlementItem) GetProfit() string {
	if x != nil {
		return x.Profit
	}
	return ""
}

func (x *SettlementItem) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

func (x *SettlementItem) GetPump() string {
	if x != nil {
		return x.Pump
	}
	return ""
}

// 批量结算请求，必须覆盖本局全部有效真人玩家且不能重复。
type SettlementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全局唯一结算编号，也是结算幂等键。
	SettlementId  string `protobuf:"bytes,1,opt,name=settlementId,proto3" json:"settlementId,omitempty"`
	RoundId       string `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameId        uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Agent         uint32 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Level         uint32 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	ReservationId string `protobuf:"bytes,6,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	BetDigest     string `protobuf:"bytes,7,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	OutcomeHash   string `protobuf:"bytes,8,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	// NORMAL 为正常赔付，VOID_REFUND 为全额退回下注并关闭本局。
	Mode          string            `protobuf:"bytes,9,opt,name=mode,proto3" json:"mode,omitempty"`
	Items         []*SettlementItem `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementRequest) Reset() {
	*x = SettlementRequest{}
	mi := &file_lottery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementRequest) ProtoMessage() {}

func (x *SettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementRequest.ProtoReflect.Descriptor instead.
func (*SettlementRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{10}
}

func (x *SettlementRequest) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *SettlementRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SettlementRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SettlementRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *SettlementRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SettlementRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *SettlementRequest) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *SettlementRequest) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *SettlementRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SettlementRequest) GetItems() []*SettlementItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单个玩家的结算结果。
type SettlementItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Code          ErrorCode              `protobuf:"varint,2,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementItemResult) Reset() {
	*x = SettlementItemResult{}
	mi := &file_lottery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementItemResult) ProtoMessage() {}

func (x *SettlementItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementItemResult.ProtoReflect.Descriptor instead.
func (*SettlementItemResult) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{11}
}

func (x *SettlementItemResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SettlementItemResult) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *SettlementItemResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SettlementItemResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 批量结算响应。
type SettlementResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          ErrorCode               `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	RoundId       string                  `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	State         string                  `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	SettlementId  string                  `protobuf:"bytes,4,opt,name=settlementId,proto3" json:"settlementId,omitempty"`
	Items         []*SettlementItemResult `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementResponse) Reset() {
	*x = SettlementResponse{}
	mi := &file_lottery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResponse) ProtoMessage() {}

func (x *SettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResponse.ProtoReflect.Descriptor instead.
func (*SettlementResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{12}
}

func (x *SettlementResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *SettlementResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SettlementResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SettlementResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *SettlementResponse) GetItems() []*SettlementItemResult {
	if x != nil {
		return x.Items
	}
	return nil
}

// 按牌局编号查询资金状态。
type GetRoundFinanceStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoundFinanceStateReq) Reset() {
	*x = GetRoundFinanceStateReq{}
	mi := &file_lottery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundFinanceStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundFinanceStateReq) ProtoMessage() {}

func (x *GetRoundFinanceStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundFinanceStateReq.ProtoReflect.Descriptor instead.
func (*GetRoundFinanceStateReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{13}
}

func (x *GetRoundFinanceStateReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

// 牌局资金状态快照。
type GetRoundFinanceStateResp struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	RoundId string                 `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	// BETTING、RESERVED、SETTLED、VOIDED 或 EXPIRED。
	State         string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	BetDigest     string `protobuf:"bytes,4,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	ReservationId string `protobuf:"bytes,5,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	OutcomeHash   string `protobuf:"bytes,6,opt,name=outcomeHash,proto3" json:"outcomeHash,omitempty"`
	ExpiresAt     int64  `protobuf:"varint,7,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	SettlementId  string `protobuf:"bytes,8,opt,name=settlementId,proto3" json:"settlementId,omitempty"`
	// 本局全部已接受下注换算后的 CNY 总额。
	TotalBetCny string `protobuf:"bytes,9,opt,name=totalBetCny,proto3" json:"totalBetCny,omitempty"`
	// 当前预留记录的 CNY 金额。
	TotalReservedCny string        `protobuf:"bytes,10,opt,name=totalReservedCny,proto3" json:"totalReservedCny,omitempty"`
	ReservationMode  string        `protobuf:"bytes,11,opt,name=reservationMode,proto3" json:"reservationMode,omitempty"`
	ReservedItems    []*PrePayItem `protobuf:"bytes,12,rep,name=reservedItems,proto3" json:"reservedItems,omitempty"`
	// 本局下注修订号；取消成功后递增，新 betId 必须带上该 revision。
	BetRevision   int64 `protobuf:"varint,13,opt,name=betRevision,proto3" json:"betRevision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoundFinanceStateResp) Reset() {
	*x = GetRoundFinanceStateResp{}
	mi := &file_lottery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundFinanceStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundFinanceStateResp) ProtoMessage() {}

func (x *GetRoundFinanceStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundFinanceStateResp.ProtoReflect.Descriptor instead.
func (*GetRoundFinanceStateResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{14}
}

func (x *GetRoundFinanceStateResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetRoundFinanceStateResp) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetOutcomeHash() string {
	if x != nil {
		return x.OutcomeHash
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetRoundFinanceStateResp) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetTotalBetCny() string {
	if x != nil {
		return x.TotalBetCny
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetTotalReservedCny() string {
	if x != nil {
		return x.TotalReservedCny
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetReservationMode() string {
	if x != nil {
		return x.ReservationMode
	}
	return ""
}

func (x *GetRoundFinanceStateResp) GetReservedItems() []*PrePayItem {
	if x != nil {
		return x.ReservedItems
	}
	return nil
}

func (x *GetRoundFinanceStateResp) GetBetRevision() int64 {
	if x != nil {
		return x.BetRevision
	}
	return 0
}

type CancelBetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 强幂等键：重复请求不重复退款、不重复冲销 agent_effect。
	RequestId    string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RoundId      string `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameId       uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Agent        uint32 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Level        uint32 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	UserId       uint32 `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	CurrencyType string `protobuf:"bytes,7,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 调用方看到的下注摘要；用于发现本地与资金侧不一致。
	ExpectedBetDigest string `protobuf:"bytes,8,opt,name=expectedBetDigest,proto3" json:"expectedBetDigest,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelBetRequest) Reset() {
	*x = CancelBetRequest{}
	mi := &file_lottery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBetRequest) ProtoMessage() {}

func (x *CancelBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBetRequest.ProtoReflect.Descriptor instead.
func (*CancelBetRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{15}
}

func (x *CancelBetRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelBetRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *CancelBetRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CancelBetRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *CancelBetRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CancelBetRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelBetRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *CancelBetRequest) GetExpectedBetDigest() string {
	if x != nil {
		return x.ExpectedBetDigest
	}
	return ""
}

type CancelBetResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 资金侧按本局该玩家全部 ACTIVE 投注汇总的退款金额。
	RefundAmount string `protobuf:"bytes,3,opt,name=refundAmount,proto3" json:"refundAmount,omitempty"`
	// 退款后的玩家钱包余额（与 SettlementItemResult.currency 同口径）。
	Currency       string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	BetDigest      string   `protobuf:"bytes,5,opt,name=betDigest,proto3" json:"betDigest,omitempty"`
	BetRevision    int64    `protobuf:"varint,6,opt,name=betRevision,proto3" json:"betRevision,omitempty"`
	CanceledBetIds []string `protobuf:"bytes,7,rep,name=canceledBetIds,proto3" json:"canceledBetIds,omitempty"`
	RoundId        string   `protobuf:"bytes,8,opt,name=roundId,proto3" json:"roundId,omitempty"`
	// 成功后仍为 BETTING。
	State         string `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	Reason        string `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBetResponse) Reset() {
	*x = CancelBetResponse{}
	mi := &file_lottery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBetResponse) ProtoMessage() {}

func (x *CancelBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBetResponse.ProtoReflect.Descriptor instead.
func (*CancelBetResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{16}
}

func (x *CancelBetResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *CancelBetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelBetResponse) GetRefundAmount() string {
	if x != nil {
		return x.RefundAmount
	}
	return ""
}

func (x *CancelBetResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CancelBetResponse) GetBetDigest() string {
	if x != nil {
		return x.BetDigest
	}
	return ""
}

func (x *CancelBetResponse) GetBetRevision() int64 {
	if x != nil {
		return x.BetRevision
	}
	return 0
}

func (x *CancelBetResponse) GetCanceledBetIds() []string {
	if x != nil {
		return x.CanceledBetIds
	}
	return nil
}

func (x *CancelBetResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *CancelBetResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CancelBetResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 单个控制候选：由游戏服预先生成完整结果后，仅上送经济摘要。
type PoolControlCandidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 候选唯一编号，例如 win / natural / lose。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// NATURAL / PLAYER_WIN / PLAYER_LOSE；可空，空则按 id 推断。
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// 该候选下真人总下注（玩家币种）。
	BetAmount string `protobuf:"bytes,3,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	// 该候选下真人总返还 payout（玩家币种，不是净利润）。
	Payout        string `protobuf:"bytes,4,opt,name=payout,proto3" json:"payout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolControlCandidate) Reset() {
	*x = PoolControlCandidate{}
	mi := &file_lottery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolControlCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolControlCandidate) ProtoMessage() {}

func (x *PoolControlCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolControlCandidate.ProtoReflect.Descriptor instead.
func (*PoolControlCandidate) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{17}
}

func (x *PoolControlCandidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PoolControlCandidate) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PoolControlCandidate) GetBetAmount() string {
	if x != nil {
		return x.BetAmount
	}
	return ""
}

func (x *PoolControlCandidate) GetPayout() string {
	if x != nil {
		return x.Payout
	}
	return ""
}

// 水池控制决策请求。不依赖已有 finance round，可在下注前调用。
type GetPoolControlDecisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求编号，用于审计；建议同时作为 decisionId 幂等关联键。
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// 可选牌局编号，仅审计用。
	RoundId string `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	GameId  uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Agent   uint32 `protobuf:"varint,4,opt,name=agent,proto3" json:"agent,omitempty"`
	Level   uint32 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	// 金额币种；换算 CNY 后参与可赔付判断。
	CurrencyType string `protobuf:"bytes,6,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	// 可选：用于可赔付公式中的玩家统计；0 表示仅按水池水位判断。
	UserId uint32 `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`
	// 至少 1 个候选；通常为 win/natural/lose 三套。
	Candidates []*PoolControlCandidate `protobuf:"bytes,8,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// 可选偏好模式；仅当该模式候选可赔付时优先采用。
	PreferredMode string `protobuf:"bytes,9,opt,name=preferredMode,proto3" json:"preferredMode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolControlDecisionRequest) Reset() {
	*x = GetPoolControlDecisionRequest{}
	mi := &file_lottery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolControlDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolControlDecisionRequest) ProtoMessage() {}

func (x *GetPoolControlDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolControlDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetPoolControlDecisionRequest) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{18}
}

func (x *GetPoolControlDecisionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetPoolControlDecisionRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetPoolControlDecisionRequest) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetPoolControlDecisionRequest) GetAgent() uint32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *GetPoolControlDecisionRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetPoolControlDecisionRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *GetPoolControlDecisionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPoolControlDecisionRequest) GetCandidates() []*PoolControlCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GetPoolControlDecisionRequest) GetPreferredMode() string {
	if x != nil {
		return x.PreferredMode
	}
	return ""
}

// 水池控制决策响应。
type GetPoolControlDecisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	// NATURAL / PLAYER_WIN / PLAYER_LOSE。
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// 选中的候选 id。
	SelectedCandidateId string `protobuf:"bytes,3,opt,name=selectedCandidateId,proto3" json:"selectedCandidateId,omitempty"`
	// 选中候选的 payout（玩家币种原样回传）。
	MaxPayout string `protobuf:"bytes,4,opt,name=maxPayout,proto3" json:"maxPayout,omitempty"`
	// 本次决策编号，供游戏服写入 controlPlan / 审计。
	DecisionId string `protobuf:"bytes,5,opt,name=decisionId,proto3" json:"decisionId,omitempty"`
	// 决策原因：OK / NO_CANDIDATE / POOL_TIGHT_FALLBACK_LOSE / PREFERRED_UNAVAILABLE 等。
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// 选中候选换算后的 CNY 净赔付 max(0, payout-bet)。
	SelectedNetPayoutCny string `protobuf:"bytes,7,opt,name=selectedNetPayoutCny,proto3" json:"selectedNetPayoutCny,omitempty"`
	// 当前可用水池 CNY 快照（仅参考，非锁定额度）。
	PoolAvailableCny string `protobuf:"bytes,8,opt,name=poolAvailableCny,proto3" json:"poolAvailableCny,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPoolControlDecisionResponse) Reset() {
	*x = GetPoolControlDecisionResponse{}
	mi := &file_lottery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolControlDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolControlDecisionResponse) ProtoMessage() {}

func (x *GetPoolControlDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolControlDecisionResponse.ProtoReflect.Descriptor instead.
func (*GetPoolControlDecisionResponse) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{19}
}

func (x *GetPoolControlDecisionResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetPoolControlDecisionResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetPoolControlDecisionResponse) GetSelectedCandidateId() string {
	if x != nil {
		return x.SelectedCandidateId
	}
	return ""
}

func (x *GetPoolControlDecisionResponse) GetMaxPayout() string {
	if x != nil {
		return x.MaxPayout
	}
	return ""
}

func (x *GetPoolControlDecisionResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *GetPoolControlDecisionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetPoolControlDecisionResponse) GetSelectedNetPayoutCny() string {
	if x != nil {
		return x.SelectedNetPayoutCny
	}
	return ""
}

func (x *GetPoolControlDecisionResponse) GetPoolAvailableCny() string {
	if x != nil {
		return x.PoolAvailableCny
	}
	return ""
}

var File_lottery_proto protoreflect.FileDescriptor

const file_lottery_proto_rawDesc = "" +
	"\n" +
	"\rlottery.proto\x12\alottery\x1a\n" +
	"base.proto\"\x8b\x01\n" +
	"\aBetItem\x12\x14\n" +
	"\x05betId\x18\x01 \x01(\tR\x05betId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12\"\n" +
	"\fcurrencyType\x18\x03 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x16\n" +
	"\x06areaId\x18\x05 \x01(\tR\x06areaId\"\xbc\x01\n" +
	"\n" +
	"BetRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12&\n" +
	"\x05items\x18\b \x03(\v2\x10.lottery.BetItemR\x05itemsJ\x04\b\x06\x10\aJ\x04\b\a\x10\b\"\xb5\x01\n" +
	"\rBetItemResult\x12\x14\n" +
	"\x05betId\x18\x01 \x01(\tR\x05betId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12$\n" +
	"\x04code\x18\x03 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xaf\x01\n" +
	"\vBetResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tbetDigest\x18\x04 \x01(\tR\tbetDigest\x12,\n" +
	"\x05items\x18\x05 \x03(\v2\x16.lottery.BetItemResultR\x05items\"`\n" +
	"\n" +
	"PrePayItem\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\fcurrencyType\x18\x02 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06payout\x18\x03 \x01(\tR\x06payout\"\xc8\x02\n" +
	"\rPrePayRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x1c\n" +
	"\tbetDigest\x18\x06 \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\a \x01(\tR\voutcomeHash\x12&\n" +
	"\x0etimeoutSeconds\x18\b \x01(\rR\x0etimeoutSeconds\x12)\n" +
	"\x05items\x18\t \x03(\v2\x13.lottery.PrePayItemR\x05items\x12(\n" +
	"\x0freservationMode\x18\n" +
	" \x01(\tR\x0freservationMode\"\xee\x02\n" +
	"\x0ePrePayResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\aroundId\x18\x03 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12$\n" +
	"\rreservationId\x18\x05 \x01(\tR\rreservationId\x12&\n" +
	"\x0etotalPayoutCny\x18\x06 \x01(\tR\x0etotalPayoutCny\x12\x1c\n" +
	"\texpiresAt\x18\a \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1c\n" +
	"\tbetDigest\x18\t \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\n" +
	" \x01(\tR\voutcomeHash\x12(\n" +
	"\x0freservationMode\x18\v \x01(\tR\x0freservationMode\"\xa1\x02\n" +
	"\x17RenewReservationRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12$\n" +
	"\rreservationId\x18\x06 \x01(\tR\rreservationId\x12\x1c\n" +
	"\tbetDigest\x18\a \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\b \x01(\tR\voutcomeHash\x12$\n" +
	"\rextendSeconds\x18\t \x01(\rR\rextendSeconds\"\xd0\x02\n" +
	"\x18RenewReservationResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\aroundId\x18\x03 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12$\n" +
	"\rreservationId\x18\x05 \x01(\tR\rreservationId\x12\x1c\n" +
	"\texpiresAt\x18\x06 \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1c\n" +
	"\tbetDigest\x18\b \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\t \x01(\tR\voutcomeHash\x12(\n" +
	"\x0freservationMode\x18\n" +
	" \x01(\tR\x0freservationMode\"\xc6\x01\n" +
	"\x0eSettlementItem\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\fcurrencyType\x18\x02 \x01(\tR\fcurrencyType\x12\x1c\n" +
	"\tbetAmount\x18\x03 \x01(\tR\tbetAmount\x12\x16\n" +
	"\x06payout\x18\x04 \x01(\tR\x06payout\x12\x16\n" +
	"\x06profit\x18\x05 \x01(\tR\x06profit\x12\x16\n" +
	"\x06record\x18\x06 \x01(\tR\x06record\x12\x12\n" +
	"\x04pump\x18\a \x01(\tR\x04pump\"\xbe\x02\n" +
	"\x11SettlementRequest\x12\"\n" +
	"\fsettlementId\x18\x01 \x01(\tR\fsettlementId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12$\n" +
	"\rreservationId\x18\x06 \x01(\tR\rreservationId\x12\x1c\n" +
	"\tbetDigest\x18\a \x01(\tR\tbetDigest\x12 \n" +
	"\voutcomeHash\x18\b \x01(\tR\voutcomeHash\x12\x12\n" +
	"\x04mode\x18\t \x01(\tR\x04mode\x12-\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x17.lottery.SettlementItemR\x05items\"\x8a\x01\n" +
	"\x14SettlementItemResult\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12$\n" +
	"\x04code\x18\x02 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xc3\x01\n" +
	"\x12SettlementResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\"\n" +
	"\fsettlementId\x18\x04 \x01(\tR\fsettlementId\x123\n" +
	"\x05items\x18\x05 \x03(\v2\x1d.lottery.SettlementItemResultR\x05items\"3\n" +
	"\x17GetRoundFinanceStateReq\x12\x18\n" +
	"\aroundId\x18\x01 \x01(\tR\aroundId\"\xed\x03\n" +
	"\x18GetRoundFinanceStateResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tbetDigest\x18\x04 \x01(\tR\tbetDigest\x12$\n" +
	"\rreservationId\x18\x05 \x01(\tR\rreservationId\x12 \n" +
	"\voutcomeHash\x18\x06 \x01(\tR\voutcomeHash\x12\x1c\n" +
	"\texpiresAt\x18\a \x01(\x03R\texpiresAt\x12\"\n" +
	"\fsettlementId\x18\b \x01(\tR\fsettlementId\x12 \n" +
	"\vtotalBetCny\x18\t \x01(\tR\vtotalBetCny\x12*\n" +
	"\x10totalReservedCny\x18\n" +
	" \x01(\tR\x10totalReservedCny\x12(\n" +
	"\x0freservationMode\x18\v \x01(\tR\x0freservationMode\x129\n" +
	"\rreservedItems\x18\f \x03(\v2\x13.lottery.PrePayItemR\rreservedItems\x12 \n" +
	"\vbetRevision\x18\r \x01(\x03R\vbetRevision\"\xf8\x01\n" +
	"\x10CancelBetRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x16\n" +
	"\x06userId\x18\x06 \x01(\rR\x06userId\x12\"\n" +
	"\fcurrencyType\x18\a \x01(\tR\fcurrencyType\x12,\n" +
	"\x11expectedBetDigest\x18\b \x01(\tR\x11expectedBetDigest\"\xc3\x02\n" +
	"\x11CancelBetResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\"\n" +
	"\frefundAmount\x18\x03 \x01(\tR\frefundAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1c\n" +
	"\tbetDigest\x18\x05 \x01(\tR\tbetDigest\x12 \n" +
	"\vbetRevision\x18\x06 \x01(\x03R\vbetRevision\x12&\n" +
	"\x0ecanceledBetIds\x18\a \x03(\tR\x0ecanceledBetIds\x12\x18\n" +
	"\aroundId\x18\b \x01(\tR\aroundId\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\"p\n" +
	"\x14PoolControlCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1c\n" +
	"\tbetAmount\x18\x03 \x01(\tR\tbetAmount\x12\x16\n" +
	"\x06payout\x18\x04 \x01(\tR\x06payout\"\xbc\x02\n" +
	"\x1dGetPoolControlDecisionRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aroundId\x18\x02 \x01(\tR\aroundId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\rR\x05agent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\"\n" +
	"\fcurrencyType\x18\x06 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06userId\x18\a \x01(\rR\x06userId\x12=\n" +
	"\n" +
	"candidates\x18\b \x03(\v2\x1d.lottery.PoolControlCandidateR\n" +
	"candidates\x12$\n" +
	"\rpreferredMode\x18\t \x01(\tR\rpreferredMode\"\xc2\x02\n" +
	"\x1eGetPoolControlDecisionResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x120\n" +
	"\x13selectedCandidateId\x18\x03 \x01(\tR\x13selectedCandidateId\x12\x1c\n" +
	"\tmaxPayout\x18\x04 \x01(\tR\tmaxPayout\x12\x1e\n" +
	"\n" +
	"decisionId\x18\x05 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x122\n" +
	"\x14selectedNetPayoutCny\x18\a \x01(\tR\x14selectedNetPayoutCny\x12*\n" +
	"\x10poolAvailableCny\x18\b \x01(\tR\x10poolAvailableCny2\xa9\x04\n" +
	"\x0eLotteryService\x120\n" +
	"\x03Bet\x12\x13.lottery.BetRequest\x1a\x14.lottery.BetResponse\x129\n" +
	"\x06PrePay\x12\x16.lottery.PrePayRequest\x1a\x17.lottery.PrePayResponse\x12W\n" +
	"\x10RenewReservation\x12 .lottery.RenewReservationRequest\x1a!.lottery.RenewReservationResponse\x12E\n" +
	"\n" +
	"Settlement\x12\x1a.lottery.SettlementRequest\x1a\x1b.lottery.SettlementResponse\x12[\n" +
	"\x14GetRoundFinanceState\x12 .lottery.GetRoundFinanceStateReq\x1a!.lottery.GetRoundFinanceStateResp\x12B\n" +
	"\tCancelBet\x12\x19.lottery.CancelBetRequest\x1a\x1a.lottery.CancelBetResponse\x12i\n" +
	"\x16GetPoolControlDecision\x12&.lottery.GetPoolControlDecisionRequest\x1a'.lottery.GetPoolControlDecisionResponseB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_lottery_proto_rawDescOnce sync.Once
	file_lottery_proto_rawDescData []byte
)

func file_lottery_proto_rawDescGZIP() []byte {
	file_lottery_proto_rawDescOnce.Do(func() {
		file_lottery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)))
	})
	return file_lottery_proto_rawDescData
}

var file_lottery_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_lottery_proto_goTypes = []any{
	(*BetItem)(nil),                        // 0: lottery.BetItem
	(*BetRequest)(nil),                     // 1: lottery.BetRequest
	(*BetItemResult)(nil),                  // 2: lottery.BetItemResult
	(*BetResponse)(nil),                    // 3: lottery.BetResponse
	(*PrePayItem)(nil),                     // 4: lottery.PrePayItem
	(*PrePayRequest)(nil),                  // 5: lottery.PrePayRequest
	(*PrePayResponse)(nil),                 // 6: lottery.PrePayResponse
	(*RenewReservationRequest)(nil),        // 7: lottery.RenewReservationRequest
	(*RenewReservationResponse)(nil),       // 8: lottery.RenewReservationResponse
	(*SettlementItem)(nil),                 // 9: lottery.SettlementItem
	(*SettlementRequest)(nil),              // 10: lottery.SettlementRequest
	(*SettlementItemResult)(nil),           // 11: lottery.SettlementItemResult
	(*SettlementResponse)(nil),             // 12: lottery.SettlementResponse
	(*GetRoundFinanceStateReq)(nil),        // 13: lottery.GetRoundFinanceStateReq
	(*GetRoundFinanceStateResp)(nil),       // 14: lottery.GetRoundFinanceStateResp
	(*CancelBetRequest)(nil),               // 15: lottery.CancelBetRequest
	(*CancelBetResponse)(nil),              // 16: lottery.CancelBetResponse
	(*PoolControlCandidate)(nil),           // 17: lottery.PoolControlCandidate
	(*GetPoolControlDecisionRequest)(nil),  // 18: lottery.GetPoolControlDecisionRequest
	(*GetPoolControlDecisionResponse)(nil), // 19: lottery.GetPoolControlDecisionResponse
	(ErrorCode)(0),                         // 20: base.error_code
}
var file_lottery_proto_depIdxs = []int32{
	0,  // 0: lottery.BetRequest.items:type_name -> lottery.BetItem
	20, // 1: lottery.BetItemResult.code:type_name -> base.error_code
	20, // 2: lottery.BetResponse.code:type_name -> base.error_code
	2,  // 3: lottery.BetResponse.items:type_name -> lottery.BetItemResult
	4,  // 4: lottery.PrePayRequest.items:type_name -> lottery.PrePayItem
	20, // 5: lottery.PrePayResponse.code:type_name -> base.error_code
	20, // 6: lottery.RenewReservationResponse.code:type_name -> base.error_code
	9,  // 7: lottery.SettlementRequest.items:type_name -> lottery.SettlementItem
	20, // 8: lottery.SettlementItemResult.code:type_name -> base.error_code
	20, // 9: lottery.SettlementResponse.code:type_name -> base.error_code
	11, // 10: lottery.SettlementResponse.items:type_name -> lottery.SettlementItemResult
	20, // 11: lottery.GetRoundFinanceStateResp.code:type_name -> base.error_code
	4,  // 12: lottery.GetRoundFinanceStateResp.reservedItems:type_name -> lottery.PrePayItem
	20, // 13: lottery.CancelBetResponse.code:type_name -> base.error_code
	17, // 14: lottery.GetPoolControlDecisionRequest.candidates:type_name -> lottery.PoolControlCandidate
	20, // 15: lottery.GetPoolControlDecisionResponse.code:type_name -> base.error_code
	1,  // 16: lottery.LotteryService.Bet:input_type -> lottery.BetRequest
	5,  // 17: lottery.LotteryService.PrePay:input_type -> lottery.PrePayRequest
	7,  // 18: lottery.LotteryService.RenewReservation:input_type -> lottery.RenewReservationRequest
	10, // 19: lottery.LotteryService.Settlement:input_type -> lottery.SettlementRequest
	13, // 20: lottery.LotteryService.GetRoundFinanceState:input_type -> lottery.GetRoundFinanceStateReq
	15, // 21: lottery.LotteryService.CancelBet:input_type -> lottery.CancelBetRequest
	18, // 22: lottery.LotteryService.GetPoolControlDecision:input_type -> lottery.GetPoolControlDecisionRequest
	3,  // 23: lottery.LotteryService.Bet:output_type -> lottery.BetResponse
	6,  // 24: lottery.LotteryService.PrePay:output_type -> lottery.PrePayResponse
	8,  // 25: lottery.LotteryService.RenewReservation:output_type -> lottery.RenewReservationResponse
	12, // 26: lottery.LotteryService.Settlement:output_type -> lottery.SettlementResponse
	14, // 27: lottery.LotteryService.GetRoundFinanceState:output_type -> lottery.GetRoundFinanceStateResp
	16, // 28: lottery.LotteryService.CancelBet:output_type -> lottery.CancelBetResponse
	19, // 29: lottery.LotteryService.GetPoolControlDecision:output_type -> lottery.GetPoolControlDecisionResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_lottery_proto_init() }
func file_lottery_proto_init() {
	if File_lottery_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lottery_proto_goTypes,
		DependencyIndexes: file_lottery_proto_depIdxs,
		MessageInfos:      file_lottery_proto_msgTypes,
	}.Build()
	File_lottery_proto = out.File
	file_lottery_proto_goTypes = nil
	file_lottery_proto_depIdxs = nil
}
