// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: lottery.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotteryService_Bet_FullMethodName                  = "/lottery.LotteryService/Bet"
	LotteryService_PrePay_FullMethodName               = "/lottery.LotteryService/PrePay"
	LotteryService_RenewPrePay_FullMethodName          = "/lottery.LotteryService/RenewPrePay"
	LotteryService_ReleasePrePay_FullMethodName        = "/lottery.LotteryService/ReleasePrePay"
	LotteryService_Settlement_FullMethodName           = "/lottery.LotteryService/Settlement"
	LotteryService_GetRoundFinanceState_FullMethodName = "/lottery.LotteryService/GetRoundFinanceState"
)

// LotteryServiceClient is the client API for LotteryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryServiceClient interface {
	// 扣除玩家余额并登记本局下注；同一 roundId + betId 重试不会重复扣款。
	Bet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetResponse, error)
	// 根据冻结后的下注摘要和候选结果，申请奖池赔付预留。
	PrePay(ctx context.Context, in *PrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error)
	// 在预留到期前续租，防止长牌局的赔付额度被自动释放。
	RenewPrePay(ctx context.Context, in *RenewPrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error)
	// 在结果公开前主动释放赔付预留，不退还玩家下注。
	ReleasePrePay(ctx context.Context, in *ReleasePrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error)
	// 批量结算本局全部真人玩家，或按 VOID_REFUND 原路退回全部下注。
	Settlement(ctx context.Context, in *SettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
	// 查询本局资金状态，用于 RPC 超时、重连和服务迁移后的恢复。
	GetRoundFinanceState(ctx context.Context, in *GetRoundFinanceStateReq, opts ...grpc.CallOption) (*GetRoundFinanceStateResp, error)
}

type lotteryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryServiceClient(cc grpc.ClientConnInterface) LotteryServiceClient {
	return &lotteryServiceClient{cc}
}

func (c *lotteryServiceClient) Bet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetResponse)
	err := c.cc.Invoke(ctx, LotteryService_Bet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) PrePay(ctx context.Context, in *PrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePayResponse)
	err := c.cc.Invoke(ctx, LotteryService_PrePay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) RenewPrePay(ctx context.Context, in *RenewPrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePayResponse)
	err := c.cc.Invoke(ctx, LotteryService_RenewPrePay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) ReleasePrePay(ctx context.Context, in *ReleasePrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePayResponse)
	err := c.cc.Invoke(ctx, LotteryService_ReleasePrePay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) Settlement(ctx context.Context, in *SettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, LotteryService_Settlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) GetRoundFinanceState(ctx context.Context, in *GetRoundFinanceStateReq, opts ...grpc.CallOption) (*GetRoundFinanceStateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoundFinanceStateResp)
	err := c.cc.Invoke(ctx, LotteryService_GetRoundFinanceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServiceServer is the server API for LotteryService service.
// All implementations must embed UnimplementedLotteryServiceServer
// for forward compatibility.
type LotteryServiceServer interface {
	// 扣除玩家余额并登记本局下注；同一 roundId + betId 重试不会重复扣款。
	Bet(context.Context, *BetRequest) (*BetResponse, error)
	// 根据冻结后的下注摘要和候选结果，申请奖池赔付预留。
	PrePay(context.Context, *PrePayRequest) (*PrePayResponse, error)
	// 在预留到期前续租，防止长牌局的赔付额度被自动释放。
	RenewPrePay(context.Context, *RenewPrePayRequest) (*PrePayResponse, error)
	// 在结果公开前主动释放赔付预留，不退还玩家下注。
	ReleasePrePay(context.Context, *ReleasePrePayRequest) (*PrePayResponse, error)
	// 批量结算本局全部真人玩家，或按 VOID_REFUND 原路退回全部下注。
	Settlement(context.Context, *SettlementRequest) (*SettlementResponse, error)
	// 查询本局资金状态，用于 RPC 超时、重连和服务迁移后的恢复。
	GetRoundFinanceState(context.Context, *GetRoundFinanceStateReq) (*GetRoundFinanceStateResp, error)
	mustEmbedUnimplementedLotteryServiceServer()
}

// UnimplementedLotteryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryServiceServer struct{}

func (UnimplementedLotteryServiceServer) Bet(context.Context, *BetRequest) (*BetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bet not implemented")
}
func (UnimplementedLotteryServiceServer) PrePay(context.Context, *PrePayRequest) (*PrePayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrePay not implemented")
}
func (UnimplementedLotteryServiceServer) RenewPrePay(context.Context, *RenewPrePayRequest) (*PrePayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewPrePay not implemented")
}
func (UnimplementedLotteryServiceServer) ReleasePrePay(context.Context, *ReleasePrePayRequest) (*PrePayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleasePrePay not implemented")
}
func (UnimplementedLotteryServiceServer) Settlement(context.Context, *SettlementRequest) (*SettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Settlement not implemented")
}
func (UnimplementedLotteryServiceServer) GetRoundFinanceState(context.Context, *GetRoundFinanceStateReq) (*GetRoundFinanceStateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoundFinanceState not implemented")
}
func (UnimplementedLotteryServiceServer) mustEmbedUnimplementedLotteryServiceServer() {}
func (UnimplementedLotteryServiceServer) testEmbeddedByValue()                        {}

// UnsafeLotteryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServiceServer will
// result in compilation errors.
type UnsafeLotteryServiceServer interface {
	mustEmbedUnimplementedLotteryServiceServer()
}

func RegisterLotteryServiceServer(s grpc.ServiceRegistrar, srv LotteryServiceServer) {
	// If the following call panics, it indicates UnimplementedLotteryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotteryService_ServiceDesc, srv)
}

func _LotteryService_Bet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).Bet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_Bet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).Bet(ctx, req.(*BetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_PrePay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).PrePay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_PrePay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).PrePay(ctx, req.(*PrePayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_RenewPrePay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewPrePayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).RenewPrePay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_RenewPrePay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).RenewPrePay(ctx, req.(*RenewPrePayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_ReleasePrePay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePrePayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).ReleasePrePay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_ReleasePrePay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).ReleasePrePay(ctx, req.(*ReleasePrePayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_Settlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).Settlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_Settlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).Settlement(ctx, req.(*SettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_GetRoundFinanceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundFinanceStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).GetRoundFinanceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_GetRoundFinanceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).GetRoundFinanceState(ctx, req.(*GetRoundFinanceStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LotteryService_ServiceDesc is the grpc.ServiceDesc for LotteryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotteryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.LotteryService",
	HandlerType: (*LotteryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bet",
			Handler:    _LotteryService_Bet_Handler,
		},
		{
			MethodName: "PrePay",
			Handler:    _LotteryService_PrePay_Handler,
		},
		{
			MethodName: "RenewPrePay",
			Handler:    _LotteryService_RenewPrePay_Handler,
		},
		{
			MethodName: "ReleasePrePay",
			Handler:    _LotteryService_ReleasePrePay_Handler,
		},
		{
			MethodName: "Settlement",
			Handler:    _LotteryService_Settlement_Handler,
		},
		{
			MethodName: "GetRoundFinanceState",
			Handler:    _LotteryService_GetRoundFinanceState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery.proto",
}
