// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: lottery.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotteryService_Bet_FullMethodName                    = "/lottery.LotteryService/Bet"
	LotteryService_PrePay_FullMethodName                 = "/lottery.LotteryService/PrePay"
	LotteryService_Settlement_FullMethodName             = "/lottery.LotteryService/Settlement"
	LotteryService_GetRoundFinanceState_FullMethodName   = "/lottery.LotteryService/GetRoundFinanceState"
	LotteryService_CancelBet_FullMethodName              = "/lottery.LotteryService/CancelBet"
	LotteryService_GetPoolControlDecision_FullMethodName = "/lottery.LotteryService/GetPoolControlDecision"
)

// LotteryServiceClient is the client API for LotteryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryServiceClient interface {
	// 扣除玩家余额并登记本局下注；同一 roundId + betId 重试不会重复扣款。
	Bet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetResponse, error)
	// 根据冻结后的下注摘要和候选结果，申请奖池赔付预留。
	PrePay(ctx context.Context, in *PrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error)
	// 批量结算本局全部真人玩家，或按 VOID_REFUND 原路退回全部下注。
	Settlement(ctx context.Context, in *SettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
	// 查询本局资金状态，用于 RPC 超时确认和人工审核。
	GetRoundFinanceState(ctx context.Context, in *GetRoundFinanceStateReq, opts ...grpc.CallOption) (*GetRoundFinanceStateResp, error)
	// 百人玩家主动取消本局 ACTIVE 投注；退款金额由资金侧按 ACTIVE 投注计算，不由游戏服传入。
	// 禁止用 PrePay/Settlement/VOID_REFUND 代替本接口。成功后牌局仍保持 BETTING。
	CancelBet(ctx context.Context, in *CancelBetRequest, opts ...grpc.CallOption) (*CancelBetResponse, error)
	// 只读水池控制决策：游戏服提交 win/natural/lose 等候选的 bet/payout，
	// 资金侧根据水池可赔付能力选择一套结果。不扣款、不预留、不改账本。
	GetPoolControlDecision(ctx context.Context, in *GetPoolControlDecisionRequest, opts ...grpc.CallOption) (*GetPoolControlDecisionResponse, error)
}

type lotteryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryServiceClient(cc grpc.ClientConnInterface) LotteryServiceClient {
	return &lotteryServiceClient{cc}
}

func (c *lotteryServiceClient) Bet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetResponse)
	err := c.cc.Invoke(ctx, LotteryService_Bet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) PrePay(ctx context.Context, in *PrePayRequest, opts ...grpc.CallOption) (*PrePayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePayResponse)
	err := c.cc.Invoke(ctx, LotteryService_PrePay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) Settlement(ctx context.Context, in *SettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, LotteryService_Settlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) GetRoundFinanceState(ctx context.Context, in *GetRoundFinanceStateReq, opts ...grpc.CallOption) (*GetRoundFinanceStateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoundFinanceStateResp)
	err := c.cc.Invoke(ctx, LotteryService_GetRoundFinanceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) CancelBet(ctx context.Context, in *CancelBetRequest, opts ...grpc.CallOption) (*CancelBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelBetResponse)
	err := c.cc.Invoke(ctx, LotteryService_CancelBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) GetPoolControlDecision(ctx context.Context, in *GetPoolControlDecisionRequest, opts ...grpc.CallOption) (*GetPoolControlDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolControlDecisionResponse)
	err := c.cc.Invoke(ctx, LotteryService_GetPoolControlDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServiceServer is the server API for LotteryService service.
// All implementations must embed UnimplementedLotteryServiceServer
// for forward compatibility.
type LotteryServiceServer interface {
	// 扣除玩家余额并登记本局下注；同一 roundId + betId 重试不会重复扣款。
	Bet(context.Context, *BetRequest) (*BetResponse, error)
	// 根据冻结后的下注摘要和候选结果，申请奖池赔付预留。
	PrePay(context.Context, *PrePayRequest) (*PrePayResponse, error)
	// 批量结算本局全部真人玩家，或按 VOID_REFUND 原路退回全部下注。
	Settlement(context.Context, *SettlementRequest) (*SettlementResponse, error)
	// 查询本局资金状态，用于 RPC 超时确认和人工审核。
	GetRoundFinanceState(context.Context, *GetRoundFinanceStateReq) (*GetRoundFinanceStateResp, error)
	// 百人玩家主动取消本局 ACTIVE 投注；退款金额由资金侧按 ACTIVE 投注计算，不由游戏服传入。
	// 禁止用 PrePay/Settlement/VOID_REFUND 代替本接口。成功后牌局仍保持 BETTING。
	CancelBet(context.Context, *CancelBetRequest) (*CancelBetResponse, error)
	// 只读水池控制决策：游戏服提交 win/natural/lose 等候选的 bet/payout，
	// 资金侧根据水池可赔付能力选择一套结果。不扣款、不预留、不改账本。
	GetPoolControlDecision(context.Context, *GetPoolControlDecisionRequest) (*GetPoolControlDecisionResponse, error)
	mustEmbedUnimplementedLotteryServiceServer()
}

// UnimplementedLotteryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryServiceServer struct{}

func (UnimplementedLotteryServiceServer) Bet(context.Context, *BetRequest) (*BetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bet not implemented")
}
func (UnimplementedLotteryServiceServer) PrePay(context.Context, *PrePayRequest) (*PrePayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrePay not implemented")
}
func (UnimplementedLotteryServiceServer) Settlement(context.Context, *SettlementRequest) (*SettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Settlement not implemented")
}
func (UnimplementedLotteryServiceServer) GetRoundFinanceState(context.Context, *GetRoundFinanceStateReq) (*GetRoundFinanceStateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoundFinanceState not implemented")
}
func (UnimplementedLotteryServiceServer) CancelBet(context.Context, *CancelBetRequest) (*CancelBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBet not implemented")
}
func (UnimplementedLotteryServiceServer) GetPoolControlDecision(context.Context, *GetPoolControlDecisionRequest) (*GetPoolControlDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoolControlDecision not implemented")
}
func (UnimplementedLotteryServiceServer) mustEmbedUnimplementedLotteryServiceServer() {}
func (UnimplementedLotteryServiceServer) testEmbeddedByValue()                        {}

// UnsafeLotteryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServiceServer will
// result in compilation errors.
type UnsafeLotteryServiceServer interface {
	mustEmbedUnimplementedLotteryServiceServer()
}

func RegisterLotteryServiceServer(s grpc.ServiceRegistrar, srv LotteryServiceServer) {
	// If the following call panics, it indicates UnimplementedLotteryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotteryService_ServiceDesc, srv)
}

func _LotteryService_Bet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).Bet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_Bet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).Bet(ctx, req.(*BetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_PrePay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).PrePay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_PrePay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).PrePay(ctx, req.(*PrePayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_Settlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).Settlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_Settlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).Settlement(ctx, req.(*SettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_GetRoundFinanceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundFinanceStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).GetRoundFinanceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_GetRoundFinanceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).GetRoundFinanceState(ctx, req.(*GetRoundFinanceStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_CancelBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).CancelBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_CancelBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).CancelBet(ctx, req.(*CancelBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_GetPoolControlDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolControlDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).GetPoolControlDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_GetPoolControlDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).GetPoolControlDecision(ctx, req.(*GetPoolControlDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LotteryService_ServiceDesc is the grpc.ServiceDesc for LotteryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotteryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.LotteryService",
	HandlerType: (*LotteryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bet",
			Handler:    _LotteryService_Bet_Handler,
		},
		{
			MethodName: "PrePay",
			Handler:    _LotteryService_PrePay_Handler,
		},
		{
			MethodName: "Settlement",
			Handler:    _LotteryService_Settlement_Handler,
		},
		{
			MethodName: "GetRoundFinanceState",
			Handler:    _LotteryService_GetRoundFinanceState_Handler,
		},
		{
			MethodName: "CancelBet",
			Handler:    _LotteryService_CancelBet_Handler,
		},
		{
			MethodName: "GetPoolControlDecision",
			Handler:    _LotteryService_GetPoolControlDecision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery.proto",
}
