// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: player.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HumanPlayer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                // 玩家id
	Nickname       string                 `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`                     // 玩家昵称
	GameCurrency   string                 `protobuf:"bytes,3,opt,name=GameCurrency,proto3" json:"GameCurrency,omitempty"`             // 玩家游戏币数量
	Avatar         string                 `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`                         // 玩家头像
	Gender         uint32                 `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`                        // 性别
	Exp            uint32                 `protobuf:"varint,6,opt,name=Exp,proto3" json:"Exp,omitempty"`                              // 经验值
	AgentId        uint32                 `protobuf:"varint,7,opt,name=AgentId,proto3" json:"AgentId,omitempty"`                      // 代理商id
	LoginIP        string                 `protobuf:"bytes,8,opt,name=LoginIP,proto3" json:"LoginIP,omitempty"`                       // 登录ip
	LoginTimeStamp int64                  `protobuf:"varint,9,opt,name=LoginTimeStamp,proto3" json:"LoginTimeStamp,omitempty"`        // 登录时间戳
	CurrencyLimit  string                 `protobuf:"bytes,10,opt,name=CurrencyLimit,proto3" json:"CurrencyLimit,omitempty"`          // 部分游戏进入游戏前设置的带入限制
	WebSiteId      uint32                 `protobuf:"varint,11,opt,name=WebSiteId,proto3" json:"WebSiteId,omitempty"`                 // 平台id
	Factory        uint32                 `protobuf:"varint,12,opt,name=Factory,proto3" json:"Factory,omitempty"`                     //登录厂商
	HeadFrame      string                 `protobuf:"bytes,13,opt,name=head_frame,json=headFrame,proto3" json:"head_frame,omitempty"` //头像框
	Account        string                 `protobuf:"bytes,14,opt,name=Account,proto3" json:"Account,omitempty"`                      //
	CurrencyType   string                 `protobuf:"bytes,15,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Points         string                 `protobuf:"bytes,16,opt,name=points,proto3" json:"points,omitempty"`                      //积分牌
	Value          string                 `protobuf:"bytes,17,opt,name=value,proto3" json:"value,omitempty"`                        //身价
	Reward         string                 `protobuf:"bytes,18,opt,name=reward,proto3" json:"reward,omitempty"`                      //赏金
	AllTimes       int32                  `protobuf:"varint,19,opt,name=all_times,json=allTimes,proto3" json:"all_times,omitempty"` //总手数
	IsTourist      int32                  `protobuf:"varint,20,opt,name=isTourist,proto3" json:"isTourist,omitempty"`               //是否是游客账户
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HumanPlayer) Reset() {
	*x = HumanPlayer{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanPlayer) ProtoMessage() {}

func (x *HumanPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanPlayer.ProtoReflect.Descriptor instead.
func (*HumanPlayer) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *HumanPlayer) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HumanPlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *HumanPlayer) GetGameCurrency() string {
	if x != nil {
		return x.GameCurrency
	}
	return ""
}

func (x *HumanPlayer) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *HumanPlayer) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *HumanPlayer) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *HumanPlayer) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *HumanPlayer) GetLoginIP() string {
	if x != nil {
		return x.LoginIP
	}
	return ""
}

func (x *HumanPlayer) GetLoginTimeStamp() int64 {
	if x != nil {
		return x.LoginTimeStamp
	}
	return 0
}

func (x *HumanPlayer) GetCurrencyLimit() string {
	if x != nil {
		return x.CurrencyLimit
	}
	return ""
}

func (x *HumanPlayer) GetWebSiteId() uint32 {
	if x != nil {
		return x.WebSiteId
	}
	return 0
}

func (x *HumanPlayer) GetFactory() uint32 {
	if x != nil {
		return x.Factory
	}
	return 0
}

func (x *HumanPlayer) GetHeadFrame() string {
	if x != nil {
		return x.HeadFrame
	}
	return ""
}

func (x *HumanPlayer) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *HumanPlayer) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *HumanPlayer) GetPoints() string {
	if x != nil {
		return x.Points
	}
	return ""
}

func (x *HumanPlayer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *HumanPlayer) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

func (x *HumanPlayer) GetAllTimes() int32 {
	if x != nil {
		return x.AllTimes
	}
	return 0
}

func (x *HumanPlayer) GetIsTourist() int32 {
	if x != nil {
		return x.IsTourist
	}
	return 0
}

type PlayerStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Times         uint32                 `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	Bet           uint32                 `protobuf:"varint,3,opt,name=bet,proto3" json:"bet,omitempty"`
	Incr          uint32                 `protobuf:"varint,4,opt,name=incr,proto3" json:"incr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatistics) Reset() {
	*x = PlayerStatistics{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatistics) ProtoMessage() {}

func (x *PlayerStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatistics.ProtoReflect.Descriptor instead.
func (*PlayerStatistics) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerStatistics) GetTimes() uint32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *PlayerStatistics) GetBet() uint32 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *PlayerStatistics) GetIncr() uint32 {
	if x != nil {
		return x.Incr
	}
	return 0
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\x06player\"\xb8\x04\n" +
	"\vHumanPlayer\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x1a\n" +
	"\bNickname\x18\x02 \x01(\tR\bNickname\x12\"\n" +
	"\fGameCurrency\x18\x03 \x01(\tR\fGameCurrency\x12\x16\n" +
	"\x06Avatar\x18\x04 \x01(\tR\x06Avatar\x12\x16\n" +
	"\x06Gender\x18\x05 \x01(\rR\x06Gender\x12\x10\n" +
	"\x03Exp\x18\x06 \x01(\rR\x03Exp\x12\x18\n" +
	"\aAgentId\x18\a \x01(\rR\aAgentId\x12\x18\n" +
	"\aLoginIP\x18\b \x01(\tR\aLoginIP\x12&\n" +
	"\x0eLoginTimeStamp\x18\t \x01(\x03R\x0eLoginTimeStamp\x12$\n" +
	"\rCurrencyLimit\x18\n" +
	" \x01(\tR\rCurrencyLimit\x12\x1c\n" +
	"\tWebSiteId\x18\v \x01(\rR\tWebSiteId\x12\x18\n" +
	"\aFactory\x18\f \x01(\rR\aFactory\x12\x1d\n" +
	"\n" +
	"head_frame\x18\r \x01(\tR\theadFrame\x12\x18\n" +
	"\aAccount\x18\x0e \x01(\tR\aAccount\x12#\n" +
	"\rcurrency_type\x18\x0f \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06points\x18\x10 \x01(\tR\x06points\x12\x14\n" +
	"\x05value\x18\x11 \x01(\tR\x05value\x12\x16\n" +
	"\x06reward\x18\x12 \x01(\tR\x06reward\x12\x1b\n" +
	"\tall_times\x18\x13 \x01(\x05R\ballTimes\x12\x1c\n" +
	"\tisTourist\x18\x14 \x01(\x05R\tisTourist\"N\n" +
	"\x10PlayerStatistics\x12\x14\n" +
	"\x05times\x18\x02 \x01(\rR\x05times\x12\x10\n" +
	"\x03bet\x18\x03 \x01(\rR\x03bet\x12\x12\n" +
	"\x04incr\x18\x04 \x01(\rR\x04incrB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_player_proto_goTypes = []any{
	(*HumanPlayer)(nil),      // 0: player.HumanPlayer
	(*PlayerStatistics)(nil), // 1: player.PlayerStatistics
}
var file_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
